(()=>{'use strict';
const URL='https://ahiatqnokyhfpailobjx.supabase.co',KEY='sb_publishable_qgwMhZPrB_3cFv3yCMcToA_9nDvHz-O';const sb=window.supabase?.createClient(URL,KEY);if(!sb)return;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let session=null,me=null,profiles=[],relations=[],blocks=[],tab='people',selected=null,holdTimer=null,previewCloseTimer=null,previewAnchor=null,previewUserId=null,longPressOpened=false;
const roleMap={master:['DEV','#5ef3ff'],admin:['ADMIN','#ff405a'],moderator:['MOD','#bb78ff'],staff:['STAFF','#65a9ff'],streamer:['STREAMER','#ff72cf'],vip1:['VIP I','#ffd65a'],vip2:['VIP II','#ffd65a'],vip3:['VIP III','#ffd65a'],member:['MEMBRO','#73ff18']};
const roleInfo=p=>{let r=p.role||'member';if(p.is_streamer)r='streamer';if(p.vip_until&&new Date(p.vip_until)>new Date())r='vip1';return roleMap[r]||roleMap.member};
const adminHammer=p=>['master','admin','moderator','staff'].includes(p.role)?'<span class="buddy-hammer" title="Cargo administrativo">🔨</span>':'';
const avatar=p=>p.custom_avatar_url||p.avatar_url||'';const name=p=>p.game_nickname_public||p.game_nickname||p.full_name||'Membro';
function relationWith(id){return relations.find(r=>r.requester_id===id||r.addressee_id===id)}function isBlocked(id){return blocks.some(b=>b.blocked_id===id)}
function card(p){const [label,color]=roleInfo(p),rel=relationWith(p.id);let action=isBlocked(p.id)?'Desbloquear':'Adicionar Buddy';if(!isBlocked(p.id)&&rel?.status==='accepted')action='Conversar';else if(!isBlocked(p.id)&&rel?.status==='pending')action=rel.requester_id===session.user.id?'Pedido enviado':'Aceitar pedido';return `<article class="buddy-person" data-user="${p.id}" style="--role:${color}"><img src="${esc(avatar(p))}" alt=""><div><strong>${esc(name(p))}${adminHammer(p)}</strong><small>${label} · LVL ${Number(p.level||1)}</small><em>● ${esc(p.presence||'offline')}</em></div><button data-quick="${p.id}">${action}</button><button class="buddy-bell" title="Notificações desligadas">🔕</button></article>`}
async function load(){const s=await sb.auth.getSession();session=s.data.session;if(!session){$('buddyLogin').hidden=false;return}$('buddyLogin').hidden=true;$('buddyApp').hidden=false;const [pr,rl,bl]=await Promise.all([sb.from('profiles').select('*').order('game_nickname'),sb.from('buddy_relations').select('*'),sb.from('user_blocks').select('*')]);profiles=pr.data||[];relations=rl.data||[];blocks=bl.data||[];me=profiles.find(p=>p.id===session.user.id);render();}
function visible(){const q=$('buddySearch').value.trim().toLowerCase();let rows=profiles.filter(p=>p.id!==session.user.id&&p.profile_public!==false);if(tab==='buddies')rows=rows.filter(p=>relationWith(p.id)?.status==='accepted');if(tab==='requests')rows=rows.filter(p=>{const r=relationWith(p.id);return r?.status==='pending'&&r.addressee_id===session.user.id});if(tab==='blocked')rows=profiles.filter(p=>isBlocked(p.id));if(q)rows=rows.filter(p=>name(p).toLowerCase().includes(q));return rows}
function render(){const rows=visible();$('buddyList').innerHTML=rows.length?rows.map(card).join(''):'<p class="buddy-none">Nenhum utilizador aqui.</p>';bindCards()}
function cancelPreviewClose(){clearTimeout(previewCloseTimer);previewCloseTimer=null}
function schedulePreviewClose(delay=300){cancelPreviewClose();previewCloseTimer=setTimeout(()=>hidePreview(true),delay)}
function bindCards(){document.querySelectorAll('.buddy-person').forEach(el=>{const id=el.dataset.user;el.onclick=e=>{if(e.target.closest('button')||longPressOpened){longPressOpened=false;return}openProfile(id)};el.onmouseenter=e=>{cancelPreviewClose();showPreview(id,e.currentTarget)};el.onmouseleave=()=>schedulePreviewClose(300);el.ontouchstart=()=>{longPressOpened=false;clearTimeout(holdTimer);holdTimer=setTimeout(()=>{longPressOpened=true;showPreview(id,el)},2000)};el.ontouchend=()=>clearTimeout(holdTimer);el.ontouchcancel=()=>clearTimeout(holdTimer)});document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=e=>{e.stopPropagation();quickAction(b.dataset.quick)})}
function positionPreview(anchor){const box=$('buddyPreview');if(!box||box.hidden||!anchor)return;const r=anchor.getBoundingClientRect(),gap=4,width=Math.min(290,innerWidth-16),left=Math.max(8,Math.min(innerWidth-width-8,r.left+16));box.style.width=width+'px';box.style.left=left+'px';box.style.top=Math.min(innerHeight-box.offsetHeight-8,r.bottom+gap)+'px'}
function showPreview(id,anchor){const p=profiles.find(x=>x.id===id);if(!p)return;cancelPreviewClose();previewAnchor=anchor;previewUserId=id;const [label,color]=roleInfo(p),box=$('buddyPreview');box.innerHTML=`<div style="--role:${color}"><img src="${esc(avatar(p))}" alt=""><h3>${esc(name(p))}${adminHammer(p)}</h3><b>${label} · LVL ${p.level||1}</b><p>${esc(p.presence||'offline')}</p><section><button data-preview-profile>Abrir perfil</button><button data-preview-add>＋</button></section></div>`;box.hidden=false;box.onmouseenter=cancelPreviewClose;box.onmouseleave=()=>schedulePreviewClose(300);box.ontouchstart=cancelPreviewClose;positionPreview(anchor);box.querySelector('[data-preview-profile]').onclick=e=>{e.stopPropagation();openProfile(id)};box.querySelector('[data-preview-add]').onclick=e=>{e.stopPropagation();quickAction(id)}}
function hidePreview(force=false){if(!force&&previewCloseTimer)return;cancelPreviewClose();const box=$('buddyPreview');if(box)box.hidden=true;previewAnchor=null;previewUserId=null}
window.addEventListener('resize',()=>previewAnchor&&positionPreview(previewAnchor));window.addEventListener('scroll',()=>previewAnchor&&positionPreview(previewAnchor),true);document.addEventListener('pointerdown',e=>{const box=$('buddyPreview');if(!box||box.hidden)return;if(!box.contains(e.target)&&!e.target.closest('.buddy-person'))hidePreview(true)});
async function quickAction(id){if(isBlocked(id)){await sb.from('user_blocks').delete().eq('blocker_id',session.user.id).eq('blocked_id',id);return load();}const r=relationWith(id);if(!r){await sb.from('buddy_relations').insert({requester_id:session.user.id,addressee_id:id});return load()}if(r.status==='pending'&&r.addressee_id===session.user.id){await sb.from('buddy_relations').update({status:'accepted',updated_at:new Date().toISOString()}).eq('id',r.id);return load()}if(r.status==='accepted')return openChat(id);}
function openProfile(id){hidePreview();const p=profiles.find(x=>x.id===id);if(!p)return;const [label,color]=roleInfo(p);$('buddyProfileModal').innerHTML=`<div class="buddy-modal-backdrop" data-close></div><article style="--role:${color}"><button data-close>×</button><img src="${esc(avatar(p))}"><div><small>PERFIL DA COMUNIDADE</small><h2>${esc(name(p))}${adminHammer(p)}</h2><strong>${label} · LVL ${p.level||1}</strong><p>${esc(p.public_bio||'Sem biografia.')}</p><dl><div><dt>Jogo</dt><dd>${esc(p.main_game||'—')}</dd></div><div><dt>Música</dt><dd>${esc(p.favorite_music||'—')}</dd></div><div><dt>Tempo ativo</dt><dd>${Math.floor((p.active_seconds||0)/3600)}h</dd></div><div><dt>AFK</dt><dd>${Math.floor((p.afk_seconds||0)/3600)}h</dd></div></dl><footer><button data-add>Adicionar Buddy</button><button data-chat>Conversar</button><button data-block>Bloquear</button><button data-report>Reportar</button></footer></div></article>`;$('buddyProfileModal').hidden=false;$('buddyProfileModal').querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>$('buddyProfileModal').hidden=true);$('buddyProfileModal').querySelector('[data-add]').onclick=()=>quickAction(id);$('buddyProfileModal').querySelector('[data-chat]').onclick=()=>openChat(id);$('buddyProfileModal').querySelector('[data-block]').onclick=()=>blockUser(id);$('buddyProfileModal').querySelector('[data-report]').onclick=()=>reportUser(id)}
async function openChat(id){selected=profiles.find(p=>p.id===id);if(!selected)return;$('buddyProfileModal').hidden=true;$('buddyEmpty').hidden=true;$('buddyConversation').hidden=false;const [label,color]=roleInfo(selected);$('buddyChatHead').innerHTML=`<img src="${esc(avatar(selected))}"><div><strong style="color:${color}">${esc(name(selected))}${adminHammer(selected)}</strong><small>${label} · ${esc(selected.presence||'offline')}</small></div><button data-profile>Ver perfil</button><button data-block>Bloquear</button><button data-delete>Apagar conversa</button>`;$('buddyChatHead').querySelector('[data-profile]').onclick=()=>openProfile(id);$('buddyChatHead').querySelector('[data-block]').onclick=()=>blockUser(id);$('buddyChatHead').querySelector('[data-delete]').onclick=deleteConversation;await loadMessages()}
async function loadMessages(){if(!selected)return;const {data}=await sb.from('private_messages').select('*').or(`and(sender_id.eq.${session.user.id},receiver_id.eq.${selected.id}),and(sender_id.eq.${selected.id},receiver_id.eq.${session.user.id})`).order('created_at');$('buddyMessages').innerHTML=(data||[]).filter(m=>!(m.sender_id===session.user.id?m.hidden_by_sender:m.hidden_by_receiver)).map(m=>`<p class="${m.sender_id===session.user.id?'mine':'theirs'}">${esc(m.body)}<small>${new Date(m.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></p>`).join('');$('buddyMessages').scrollTop=$('buddyMessages').scrollHeight}
$('buddyMessageForm').onsubmit=async e=>{e.preventDefault();const input=$('buddyMessageInput'),body=input.value.trim();if(!body||!selected)return;const {error}=await sb.from('private_messages').insert({sender_id:session.user.id,receiver_id:selected.id,body});if(error)return alert(error.message);input.value='';loadMessages()};
async function blockUser(id){if(!confirm('Bloquear este utilizador?'))return;await sb.from('user_blocks').upsert({blocker_id:session.user.id,blocked_id:id});const r=relationWith(id);if(r)await sb.from('buddy_relations').delete().eq('id',r.id);$('buddyProfileModal').hidden=true;selected=null;$('buddyConversation').hidden=true;$('buddyEmpty').hidden=false;load()}
async function deleteConversation(){if(!selected||!confirm('Apagar esta conversa apenas para ti?'))return;const {data}=await sb.from('private_messages').select('id,sender_id,receiver_id').or(`and(sender_id.eq.${session.user.id},receiver_id.eq.${selected.id}),and(sender_id.eq.${selected.id},receiver_id.eq.${session.user.id})`);for(const m of data||[])await sb.from('private_messages').update(m.sender_id===session.user.id?{hidden_by_sender:true}:{hidden_by_receiver:true}).eq('id',m.id);loadMessages()}
function reportUser(id){const p=profiles.find(x=>x.id===id),box=$('buddyReportModal');box.innerHTML=`<div class="buddy-modal-backdrop" data-close></div><form><button type="button" data-close>×</button><h3>Reportar ${esc(name(p))}</h3><select required><option value="">Motivo</option><option value="assedio">Assédio</option><option value="spam">Spam</option><option value="ameaca">Ameaça</option><option value="conteudo_improprio">Conteúdo impróprio</option><option value="perfil_falso">Perfil falso</option><option value="outro">Outro</option></select><textarea maxlength="1000" placeholder="Detalhes opcionais"></textarea><button>Enviar denúncia</button></form>`;box.hidden=false;box.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>box.hidden=true);box.querySelector('form').onsubmit=async e=>{e.preventDefault();await sb.from('user_reports').insert({reporter_id:session.user.id,reported_id:id,reason:e.target.querySelector('select').value,details:e.target.querySelector('textarea').value.trim()||null});box.hidden=true;alert('Denúncia enviada.')}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));render()});$('buddySearch').oninput=render;sb.channel('buddy-v93').on('postgres_changes',{event:'*',schema:'public',table:'private_messages'},()=>selected&&loadMessages()).subscribe();load();})();
