(()=>{'use strict';
const URL='https://ahiatqnokyhfpailobjx.supabase.co',KEY='sb_publishable_qgwMhZPrB_3cFv3yCMcToA_9nDvHz-O';const sb=window.supabase?.createClient(URL,KEY);if(!sb)return;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let session=null,me=null,profiles=[],relations=[],blocks=[],tab='people',selected=null,holdTimer=null,previewCloseTimer=null,previewAnchor=null,previewUserId=null,longPressOpened=false,privateChannel=null,messagePollTimer=null,lastMessageSignature='',renderedMessageIds=new Set();
function syncMobileViewport(){const h=Math.round(window.visualViewport?.height||window.innerHeight);document.documentElement.style.setProperty('--buddy-visible-height',h+'px');if(selected&&innerWidth<=760)requestAnimationFrame(()=>{const box=$('buddyMessages');if(box)box.scrollTop=box.scrollHeight})}
window.visualViewport?.addEventListener('resize',syncMobileViewport);window.visualViewport?.addEventListener('scroll',syncMobileViewport);window.addEventListener('resize',syncMobileViewport);syncMobileViewport();
const roleMap={master:['DEV','#5ef3ff'],admin:['ADMIN','#ff405a'],moderator:['MOD','#bb78ff'],staff:['STAFF','#65a9ff'],streamer:['STREAMER','#ff72cf'],vip1:['VIP I','#ffd65a'],vip2:['VIP II','#ffd65a'],vip3:['VIP III','#ffd65a'],vip:['VIP','#ffd65a'],supporter:['APOIADOR','#73ff18'],member:['MEMBRO','#f6f8fb']};
const roleInfo=p=>{let r=p.role||'member';if(p.is_streamer)r='streamer';if(p.vip_until&&new Date(p.vip_until)>new Date())r='vip1';return roleMap[r]||roleMap.member};
const adminHammer=p=>['master','admin','moderator','staff'].includes(p.role)?'<span class="buddy-hammer" title="Cargo administrativo">🔨</span>':'';
const avatar=p=>p.custom_avatar_url||p.avatar_url||'';const name=p=>p.game_nickname_public||p.game_nickname||p.full_name||'Membro';
const icon=(type)=>{const common='viewBox="0 0 24 24" aria-hidden="true" focusable="false"';const paths={add:'<path d="M15 12a4 4 0 1 0-4-4 4 4 0 0 0 4 4Zm-4 2c-3.31 0-6 1.79-6 4v1h8.2a6.3 6.3 0 0 1-.2-1.5 6.47 6.47 0 0 1 .43-2.32A10.5 10.5 0 0 0 11 14Zm8-1v2h-2v2h2v2h2v-2h2v-2h-2v-2Z"/>',chat:'<path d="M4 4h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H9l-5 4v-4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Zm2 5h12V7H6Zm0 4h9v-2H6Z"/>',bell:'<path d="M12 22a2.5 2.5 0 0 0 2.35-1.67h-4.7A2.5 2.5 0 0 0 12 22Zm7-6-2-2v-3a5 5 0 0 0-4-4.9V4h-2v2.1A5 5 0 0 0 7 11v3l-2 2v2h14Z"/>',mute:'<path d="M12 22a2.5 2.5 0 0 0 2.35-1.67h-4.7A2.5 2.5 0 0 0 12 22Zm5-8v-3a5 5 0 0 0-7.9-4.08L17 14.82ZM4.27 3 3 4.27l4 4V14l-2 2v2h9.73l5 5L21 21.73Z"/>',group:'<path d="M8 12a4 4 0 1 0-4-4 4 4 0 0 0 4 4Zm8-1a3 3 0 1 0-3-3 3 3 0 0 0 3 3ZM8 14c-4 0-7 2-7 4.5V20h10.2a6 6 0 0 1-.2-1.5 6.6 6.6 0 0 1 1.2-3.8A11.8 11.8 0 0 0 8 14Zm11 0v2h-2v2h2v2h2v-2h2v-2h-2v-2Z"/>',profile:'<path d="M12 12a5 5 0 1 0-5-5 5 5 0 0 0 5 5Zm0 2c-4.42 0-8 2.24-8 5v1h16v-1c0-2.76-3.58-5-8-5Z"/>',back:'<path d="m15.5 5-7 7 7 7 1.5-1.5-5.5-5.5 5.5-5.5Z"/>',check:'<path d="m9.2 16.2-4.4-4.4-1.6 1.6 6 6L21 7.6 19.4 6Z"/>',cancel:'<path d="M18.3 5.7 12 12l6.3 6.3-1.4 1.4L10.6 13.4 4.3 19.7l-1.4-1.4L9.2 12 2.9 5.7l1.4-1.4 6.3 6.3 6.3-6.3Z"/>'};return `<svg class="buddy-svg buddy-svg-${type}" ${common}>${paths[type]||paths.profile}</svg>`};
function presenceOf(p){const raw=String(p.presence||'').toLowerCase();if(raw==='busy'||raw==='ocupado')return 'ocupado';const stamp=p.last_seen_at?new Date(p.last_seen_at).getTime():0;if(!stamp)return p.id===session?.user?.id?'online':'offline';const age=Date.now()-stamp;if(age<90000)return 'online';if(age<300000)return 'away';return 'offline'}
function relationWith(id){return relations.find(r=>r.requester_id===id||r.addressee_id===id)}function isBlocked(id){return blocks.some(b=>b.blocked_id===id)}
function buddySoundEnabled(id){return window.TeamBuddyNotifications?.soundEnabled?.(id)??(localStorage.getItem(`tl_buddy_sound_${session?.user?.id||'anon'}_${id}`)==='1')}
function setBuddySound(id,on){if(window.TeamBuddyNotifications?.setSound)window.TeamBuddyNotifications.setSound(id,on);else localStorage.setItem(`tl_buddy_sound_${session?.user?.id||'anon'}_${id}`,on?'1':'0')}
function functionBell(id){const on=buddySoundEnabled(id);return `<button type="button" class="buddy-bell${on?' is-on':''}" data-bell="${id}" title="${on?'Som de mensagens ativado':'Som de mensagens desligado'}" aria-label="${on?'Desativar som de mensagens':'Ativar som de mensagens'}">${icon(on?'bell':'mute')}</button>`}
function card(p){const [label,color]=roleInfo(p),presence=presenceOf(p);return `<article class="buddy-person" data-user="${p.id}" style="--role:${color}" tabindex="0" role="button" aria-label="Abrir perfil de ${esc(name(p))}"><img src="${esc(avatar(p))}" alt=""><div><strong>${esc(name(p))}${adminHammer(p)}</strong><small>${label} · LVL ${Number(p.level||1)}</small><em class="buddy-presence buddy-presence-${presence}">● ${esc(presence)}</em></div></article>`}
async function load(){const s=await sb.auth.getSession();session=s.data.session;if(!session){$('buddyLogin').hidden=false;return}$('buddyLogin').hidden=true;$('buddyApp').hidden=false;const [pr,rl,bl]=await Promise.all([sb.from('profiles').select('*').order('game_nickname'),sb.from('buddy_relations').select('*'),sb.from('user_blocks').select('*')]);profiles=pr.data||[];relations=rl.data||[];blocks=bl.data||[];me=profiles.find(p=>p.id===session.user.id);render();subscribePrivateRealtime();}
function visible(){const q=$('buddySearch').value.trim().toLowerCase();let rows=profiles.filter(p=>p.id!==session.user.id&&p.profile_public!==false);if(tab==='buddies')rows=rows.filter(p=>relationWith(p.id)?.status==='accepted');if(tab==='requests')rows=rows.filter(p=>{const r=relationWith(p.id);return r?.status==='pending'&&r.addressee_id===session.user.id});if(tab==='blocked')rows=profiles.filter(p=>isBlocked(p.id));if(q)rows=rows.filter(p=>name(p).toLowerCase().includes(q));const rank=p=>relationWith(p.id)?.status==='accepted'?0:relationWith(p.id)?.status==='pending'?1:2;return rows.sort((a,b)=>rank(a)-rank(b)||name(a).localeCompare(name(b),'pt'))}
function render(){const rows=visible();$('buddyList').innerHTML=rows.length?rows.map(card).join(''):'<p class="buddy-none">Nenhum utilizador aqui.</p>';bindCards()}
function cancelPreviewClose(){clearTimeout(previewCloseTimer);previewCloseTimer=null}
function schedulePreviewClose(delay=60){cancelPreviewClose();previewCloseTimer=setTimeout(()=>hidePreview(true),delay)}
function bindCards(){document.querySelectorAll('.buddy-person').forEach(el=>{const id=el.dataset.user,triggerParts=[el.querySelector('img'),el.querySelector('div')].filter(Boolean),open=()=>openProfile(id);el.onclick=e=>{if(longPressOpened){longPressOpened=false;return}open()};el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}};triggerParts.forEach(part=>{part.classList.add('buddy-preview-trigger');part.onmouseenter=()=>{cancelPreviewClose();showPreview(id,el)};part.onmouseleave=e=>{const box=$('buddyPreview');if(box&&!box.hidden&&box.contains(e.relatedTarget))return;schedulePreviewClose(60)}});el.ontouchstart=()=>{longPressOpened=false;clearTimeout(holdTimer);holdTimer=setTimeout(()=>{longPressOpened=true;showPreview(id,el)},1200)};el.ontouchend=()=>clearTimeout(holdTimer);el.ontouchcancel=()=>clearTimeout(holdTimer)});document.querySelectorAll('[data-quick]').forEach(b=>{let touchHandled=false;const run=e=>{e.preventDefault();e.stopPropagation();hidePreview(true);quickAction(b.dataset.quick)};b.onclick=e=>{if(touchHandled){touchHandled=false;return}run(e)};b.ontouchend=e=>{touchHandled=true;run(e);setTimeout(()=>{touchHandled=false},450)}})}
function positionPreview(anchor){const box=$('buddyPreview');if(!box||box.hidden||!anchor)return;const r=anchor.getBoundingClientRect(),gap=0,width=Math.min(290,innerWidth-16);let left;if(innerWidth>=760&&r.right+gap+width<=innerWidth-8)left=r.right+gap;else left=Math.max(8,Math.min(innerWidth-width-8,r.left+16));let top=r.bottom+gap;if(top+box.offsetHeight>innerHeight-8)top=Math.max(8,r.top-box.offsetHeight-gap);box.style.width=width+'px';box.style.left=left+'px';box.style.top=top+'px'}
function showPreview(id,anchor){const p=profiles.find(x=>x.id===id);if(!p)return;cancelPreviewClose();previewAnchor=anchor;previewUserId=id;const [label,color]=roleInfo(p),box=$('buddyPreview');box.innerHTML=`<div style="--role:${color}"><img src="${esc(avatar(p))}" alt=""><h3>${esc(name(p))}${adminHammer(p)}</h3><b>${label} · LVL ${p.level||1}</b><p>${esc(p.presence||'offline')}</p><section><button data-preview-profile>Abrir perfil</button><button data-preview-add>＋</button></section></div>`;box.hidden=false;box.onmouseenter=cancelPreviewClose;box.onmouseleave=e=>{if(previewAnchor&&previewAnchor.contains(e.relatedTarget))return;hidePreview(true)};box.ontouchstart=cancelPreviewClose;positionPreview(anchor);box.querySelector('[data-preview-profile]').onclick=e=>{e.stopPropagation();openProfile(id)};box.querySelector('[data-preview-add]').onclick=e=>{e.stopPropagation();quickAction(id)}}
function hidePreview(force=false){if(!force&&previewCloseTimer)return;cancelPreviewClose();const box=$('buddyPreview');if(box)box.hidden=true;previewAnchor=null;previewUserId=null}
window.addEventListener('resize',()=>previewAnchor&&positionPreview(previewAnchor));window.addEventListener('scroll',()=>previewAnchor&&positionPreview(previewAnchor),true);document.addEventListener('pointerdown',e=>{const box=$('buddyPreview');if(!box||box.hidden)return;if(!box.contains(e.target)&&!e.target.closest('.buddy-person'))hidePreview(true)});
async function quickAction(id){if(isBlocked(id)){await sb.from('user_blocks').delete().eq('blocker_id',session.user.id).eq('blocked_id',id);return load();}const r=relationWith(id);if(!r){await sb.from('buddy_relations').insert({requester_id:session.user.id,addressee_id:id});return load()}if(r.status==='pending'&&r.requester_id===session.user.id){await sb.from('buddy_relations').delete().eq('id',r.id);return load()}if(r.status==='pending'&&r.addressee_id===session.user.id){await sb.from('buddy_relations').update({status:'accepted',updated_at:new Date().toISOString()}).eq('id',r.id);return load()}if(r.status==='accepted')return openChat(id);}
function openProfile(id){hidePreview();const p=profiles.find(x=>x.id===id);if(!p)return;const [label,color]=roleInfo(p),rel=relationWith(id),self=id===session.user.id,blocked=isBlocked(id);let actions='';if(self){actions='<button data-edit>Editar perfil</button>'}else if(blocked){actions='<button data-add>Desbloquear</button><button data-report>Reportar</button>'}else if(rel?.status==='accepted'){actions='<button data-chat>Conversar</button><button data-remove>Remover Buddy</button><button data-block>Bloquear</button><button data-report>Reportar</button>'}else if(rel?.status==='pending'&&rel.requester_id===session.user.id){actions='<button data-add>Cancelar solicitação</button><button data-block>Bloquear</button><button data-report>Reportar</button>'}else if(rel?.status==='pending'&&rel.addressee_id===session.user.id){actions='<button data-add>Aceitar pedido</button><button data-block>Bloquear</button><button data-report>Reportar</button>'}else{actions='<button data-add>Adicionar Buddy</button><button data-block>Bloquear</button><button data-report>Reportar</button>'}$('buddyProfileModal').innerHTML=`<div class="buddy-modal-backdrop" data-close></div><article style="--role:${color}"><button data-close>×</button><img src="${esc(avatar(p))}"><div><small>PERFIL DA COMUNIDADE</small><h2>${esc(name(p))}${adminHammer(p)}</h2><strong>${label} · LVL ${p.level||1}</strong><p>${esc(p.public_bio||'Sem biografia.')}</p><dl><div><dt>Jogo</dt><dd>${esc(p.main_game||'—')}</dd></div><div><dt>Música</dt><dd>${esc(p.favorite_music||'—')}</dd></div><div><dt>Tempo ativo</dt><dd>${Math.floor((p.active_seconds||0)/3600)}h</dd></div><div><dt>AFK</dt><dd>${Math.floor((p.afk_seconds||0)/3600)}h</dd></div></dl><footer>${actions}</footer></div></article>`;$('buddyProfileModal').hidden=false;const modal=$('buddyProfileModal');modal.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>modal.hidden=true);modal.querySelector('[data-add]')?.addEventListener('click',async()=>{await quickAction(id);modal.hidden=true});modal.querySelector('[data-chat]')?.addEventListener('click',()=>openChat(id));modal.querySelector('[data-remove]')?.addEventListener('click',async()=>{if(!confirm('Remover este Buddy?'))return;const current=relationWith(id);if(current)await sb.from('buddy_relations').delete().eq('id',current.id);modal.hidden=true;load()});modal.querySelector('[data-block]')?.addEventListener('click',()=>blockUser(id));modal.querySelector('[data-report]')?.addEventListener('click',()=>reportUser(id));modal.querySelector('[data-edit]')?.addEventListener('click',()=>alert('Editor de perfil entra no próximo passo.'))}

function closeConversation(e){
 if(e){e.preventDefault?.();e.stopPropagation?.()}
 stopMessagePolling();
 selected=null;lastMessageSignature='';renderedMessageIds=new Set();
 const app=$('buddyApp'),sidebar=app?.querySelector('.buddy-sidebar'),main=app?.querySelector('.buddy-main');
 app?.classList.remove('conversation-open');document.body.classList.remove('buddy-mobile-chat-open');
 if($('buddyConversation'))$('buddyConversation').hidden=true;if($('buddyEmpty'))$('buddyEmpty').hidden=false;
 if(sidebar)sidebar.style.display='';if(main){main.style.display='';main.style.marginTop=''}
 history.replaceState(null,'',location.pathname);
 requestAnimationFrame(()=>window.scrollTo({top:0,left:0,behavior:'auto'}));
}
async function openChat(id){selected=profiles.find(p=>p.id===id);if(!selected)return;hidePreview(true);$('buddyProfileModal').hidden=true;const app=$('buddyApp'),sidebar=app.querySelector('.buddy-sidebar'),main=app.querySelector('.buddy-main');$('buddyEmpty').hidden=true;$('buddyConversation').hidden=false;$('buddyConversation').classList.remove('is-minimized');app.classList.add('conversation-open');if(innerWidth<=760){sidebar.style.display='none';main.style.display='block';main.style.marginTop='0';document.body.classList.add('buddy-mobile-chat-open');syncMobileViewport();window.scrollTo({top:0,left:0,behavior:'auto'})}const [label,color]=roleInfo(selected);$('buddyChatHead').innerHTML=`<button class="buddy-chat-back buddy-icon-button" data-back aria-label="Voltar à lista">${icon('back')}</button><img src="${esc(avatar(selected))}"><div><strong style="color:${color}">${esc(name(selected))}${adminHammer(selected)}</strong><small>${label} · ${esc(presenceOf(selected))}</small></div><button class="buddy-icon-button" data-profile title="Abrir perfil" aria-label="Abrir perfil">${icon('profile')}</button><button class="buddy-icon-button" data-minimize title="Minimizar conversa" aria-label="Minimizar conversa">−</button><button class="buddy-icon-button" data-close-chat title="Fechar conversa" aria-label="Fechar conversa">×</button><button data-block>Bloquear</button><button data-delete>Apagar</button>`;const backBtn=$('buddyChatHead').querySelector('[data-back]');let backTouchAt=0;const doBack=e=>{const now=Date.now();if(e.type==='click'&&now-backTouchAt<500)return;if(e.type!=='click')backTouchAt=now;closeConversation(e)};backBtn.addEventListener('pointerup',doBack,{passive:false});backBtn.addEventListener('touchend',doBack,{passive:false});backBtn.addEventListener('click',doBack);$('buddyChatHead').querySelector('[data-profile]').onclick=()=>openProfile(id);$('buddyChatHead').querySelector('[data-minimize]').onclick=()=>{if(innerWidth<=760)return;$('buddyConversation').classList.toggle('is-minimized')};$('buddyChatHead').querySelector('[data-close-chat]').onclick=closeConversation;$('buddyChatHead').querySelector('[data-block]').onclick=()=>blockUser(id);$('buddyChatHead').querySelector('[data-delete]').onclick=deleteConversation;await loadMessages(true);startMessagePolling();requestAnimationFrame(()=>{const box=$('buddyMessages');if(box)box.scrollTop=box.scrollHeight})}
function messageBelongsToOpenChat(m){return !!(selected&&session&&[m.sender_id,m.receiver_id].includes(session.user.id)&&[m.sender_id,m.receiver_id].includes(selected.id))}
function messageMarkup(m){return `<p data-message-id="${esc(m.id)}" class="${m.sender_id===session.user.id?'mine':'theirs'}">${esc(m.body)}<small>${new Date(m.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></p>`}
function appendRealtimeMessage(m){if(!messageBelongsToOpenChat(m)||renderedMessageIds.has(String(m.id)))return;const hidden=m.sender_id===session.user.id?m.hidden_by_sender:m.hidden_by_receiver;if(hidden)return;const box=$('buddyMessages'),wasNearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<120;box.insertAdjacentHTML('beforeend',messageMarkup(m));renderedMessageIds.add(String(m.id));if(wasNearBottom||m.sender_id===session.user.id)box.scrollTop=box.scrollHeight;if(m.receiver_id===session.user.id)markOpenConversationRead()}
async function markOpenConversationRead(){if(!selected)return;await sb.from('private_messages').update({read_at:new Date().toISOString()}).eq('receiver_id',session.user.id).eq('sender_id',selected.id).is('read_at',null);window.dispatchEvent(new Event('buddy:messages-read'))}

function stopMessagePolling(){
  if(messagePollTimer){clearInterval(messagePollTimer);messagePollTimer=null}
}
function startMessagePolling(){
  stopMessagePolling();
  // Fallback leve: o Realtime continua sendo a fonte principal.
  // Se o canal falhar ou o navegador suspender eventos, atualiza a conversa aberta.
  messagePollTimer=setInterval(()=>{if(selected)loadMessages(false)},450);
}
async function loadMessages(force=false){if(!selected)return;const selectedId=selected.id;const {data,error}=await sb.from('private_messages').select('*').or(`and(sender_id.eq.${session.user.id},receiver_id.eq.${selectedId}),and(sender_id.eq.${selectedId},receiver_id.eq.${session.user.id})`).order('created_at');if(error||!selected||selected.id!==selectedId)return;const visible=(data||[]).filter(m=>!(m.sender_id===session.user.id?m.hidden_by_sender:m.hidden_by_receiver));const signature=visible.map(m=>`${m.id}:${m.created_at}:${m.hidden_by_sender}:${m.hidden_by_receiver}`).join('|');if(!force&&signature===lastMessageSignature)return;lastMessageSignature=signature;const box=$('buddyMessages'),wasNearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<90;renderedMessageIds=new Set(visible.map(m=>String(m.id)));box.innerHTML=visible.map(messageMarkup).join('');if(force||wasNearBottom)box.scrollTop=box.scrollHeight;await markOpenConversationRead()}
$('buddyMessageForm').onsubmit=async e=>{e.preventDefault();const input=$('buddyMessageInput'),body=input.value.trim();if(!body||!selected)return;const receiverId=selected.id,inputBody=body;input.value='';const {error}=await sb.from('private_messages').insert({sender_id:session.user.id,receiver_id:receiverId,body:inputBody});if(error){input.value=inputBody;return alert(error.message)}await loadMessages(true)};
async function blockUser(id){if(!confirm('Bloquear este utilizador?'))return;await sb.from('user_blocks').upsert({blocker_id:session.user.id,blocked_id:id});const r=relationWith(id);if(r)await sb.from('buddy_relations').delete().eq('id',r.id);$('buddyProfileModal').hidden=true;closeConversation();load()}
async function deleteConversation(){if(!selected||!confirm('Apagar esta conversa apenas para ti?'))return;const {data}=await sb.from('private_messages').select('id,sender_id,receiver_id').or(`and(sender_id.eq.${session.user.id},receiver_id.eq.${selected.id}),and(sender_id.eq.${selected.id},receiver_id.eq.${session.user.id})`);for(const m of data||[])await sb.from('private_messages').update(m.sender_id===session.user.id?{hidden_by_sender:true}:{hidden_by_receiver:true}).eq('id',m.id);loadMessages()}
function reportUser(id){const p=profiles.find(x=>x.id===id),box=$('buddyReportModal');box.innerHTML=`<div class="buddy-modal-backdrop" data-close></div><form><button type="button" data-close>×</button><h3>Reportar ${esc(name(p))}</h3><select required><option value="">Motivo</option><option value="assedio">Assédio</option><option value="spam">Spam</option><option value="ameaca">Ameaça</option><option value="conteudo_improprio">Conteúdo impróprio</option><option value="perfil_falso">Perfil falso</option><option value="outro">Outro</option></select><textarea maxlength="1000" placeholder="Detalhes opcionais"></textarea><button>Enviar denúncia</button></form>`;box.hidden=false;box.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>box.hidden=true);box.querySelector('form').onsubmit=async e=>{e.preventDefault();await sb.from('user_reports').insert({reporter_id:session.user.id,reported_id:id,reason:e.target.querySelector('select').value,details:e.target.querySelector('textarea').value.trim()||null});box.hidden=true;alert('Denúncia enviada.')}}
const openBuddyProfilePanel=openProfile;
openProfile=function(id){
  openBuddyProfilePanel(id);
  requestAnimationFrame(()=>{
    const p=profiles.find(x=>x.id===id),modal=$('buddyProfileModal');
    if(!p||!modal||modal.hidden)return;
    const details=modal.querySelector('article dl');
    if(!details)return;
    const status=presenceOf(p),country=p.country||p.country_code||'',games=p.main_game||p.games||'';
    const extras=[['Estado',status],['País',country],['Jogos',Array.isArray(games)?games.join(' · '):games]].filter(([,value])=>value);
    extras.forEach(([label,value])=>{const item=document.createElement('div');item.innerHTML=`<dt>${esc(label)}</dt><dd>${esc(value)}</dd>`;details.append(item)});
  });
};
function subscribePrivateRealtime(){
  if(!session)return;
  if(privateChannel)sb.removeChannel(privateChannel);
  const uid=session.user.id;
  const onInsert=payload=>{
    const row=payload.new||{};
    appendRealtimeMessage(row);
    if(messageBelongsToOpenChat(row))setTimeout(()=>loadMessages(false),80);
  };
  privateChannel=sb.channel(`buddy-private-${uid}-${Date.now()}`)
    .on('postgres_changes',{event:'INSERT',schema:'public',table:'private_messages',filter:`receiver_id=eq.${uid}`},onInsert)
    .on('postgres_changes',{event:'INSERT',schema:'public',table:'private_messages',filter:`sender_id=eq.${uid}`},onInsert)
    .on('postgres_changes',{event:'UPDATE',schema:'public',table:'private_messages'},payload=>{
      const row=payload.new||payload.old||{};
      if(messageBelongsToOpenChat(row))loadMessages(true);
    })
    .on('postgres_changes',{event:'UPDATE',schema:'public',table:'profiles'},payload=>{
      const row=payload.new||{};
      const i=profiles.findIndex(p=>p.id===row.id);
      if(i>=0)profiles[i]={...profiles[i],...row};
      if(selected?.id===row.id)selected=profiles[i];
      render();
    })
    .subscribe(status=>{
      if(status==='SUBSCRIBED'){
        if(selected)loadMessages(true);
      }else if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'||status==='CLOSED'){
        startMessagePolling();
      }
    });
}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{if(innerWidth<=760&&selected)closeConversation();tab=b.dataset.tab;$('buddyTestSound')?.addEventListener('click',async()=>{const btn=$('buddyTestSound');btn.disabled=true;const ok=await window.TeamBuddyNotifications?.testSound?.();let note=$('buddySoundStatus');if(!note){note=document.createElement('small');note.id='buddySoundStatus';note.className='buddy-sound-status';btn.insertAdjacentElement('afterend',note)}note.textContent=ok?'✓ Som reproduzido':'Não foi possível reproduzir o som';note.dataset.ok=ok?'1':'0';setTimeout(()=>note.textContent='',3500);btn.disabled=false});document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));render()});$('buddySearch').oninput=render;document.addEventListener('visibilitychange',()=>{if(!document.hidden){subscribePrivateRealtime();if(selected)loadMessages(true)}});window.addEventListener('focus',()=>{subscribePrivateRealtime();if(selected)loadMessages(true)});window.addEventListener('pageshow',()=>{subscribePrivateRealtime();if(selected)loadMessages(true)});window.addEventListener('online',()=>{subscribePrivateRealtime();if(selected)loadMessages(true)});window.TeamBuddy={isConversationOpenWith:id=>!!(selected&&selected.id===id),openChat};(async()=>{await load();const id=new URLSearchParams(location.search).get('chat');if(id&&profiles.some(p=>p.id===id))openChat(id)})();})();
