(()=>{'use strict';
const URL='https://ahiatqnokyhfpailobjx.supabase.co',KEY='sb_publishable_qgwMhZPrB_3cFv3yCMcToA_9nDvHz-O';const sb=window.supabase?.createClient(URL,KEY);if(!sb)return;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let session=null,me=null,profiles=[],relations=[],blocks=[],tab='people',selected=null,holdTimer=null,previewCloseTimer=null,previewAnchor=null,previewUserId=null,longPressOpened=false,privateChannel=null,messagePollTimer=null,lastMessageSignature='',renderedMessageIds=new Set();
function syncMobileViewport(){const h=Math.round(window.visualViewport?.height||window.innerHeight);document.documentElement.style.setProperty('--buddy-visible-height',h+'px');if(selected&&innerWidth<=760)requestAnimationFrame(()=>{const box=$('buddyMessages');if(box)box.scrollTop=box.scrollHeight})}
window.visualViewport?.addEventListener('resize',syncMobileViewport);window.visualViewport?.addEventListener('scroll',syncMobileViewport);window.addEventListener('resize',syncMobileViewport);syncMobileViewport();
const roleMap={master:['DEV','#5ef3ff'],admin:['ADMIN','#ff405a'],moderator:['MOD','#bb78ff'],staff:['STAFF','#65a9ff'],streamer:['STREAMER','#ff72cf'],vip1:['VIP I','#ffd65a'],vip2:['VIP II','#ffd65a'],vip3:['VIP III','#ffd65a'],member:['MEMBRO','#73ff18']};
const roleInfo=p=>{let r=p.role||'member';if(p.is_streamer)r='streamer';if(p.vip_until&&new Date(p.vip_until)>new Date())r='vip1';return roleMap[r]||roleMap.member};
const adminHammer=p=>['master','admin','moderator','staff'].includes(p.role)?'<span class="buddy-hammer" title="Cargo administrativo">🔨</span>':'';
const avatar=p=>p.custom_avatar_url||p.avatar_url||'';const name=p=>p.game_nickname_public||p.game_nickname||p.full_name||'Membro';
function relationWith(id){return relations.find(r=>r.requester_id===id||r.addressee_id===id)}function isBlocked(id){return blocks.some(b=>b.blocked_id===id)}
function card(p){const [label,color]=roleInfo(p),rel=relationWith(p.id);let action=isBlocked(p.id)?'Desbloquear':'Adicionar Buddy';if(!isBlocked(p.id)&&rel?.status==='accepted')action='Conversar';else if(!isBlocked(p.id)&&rel?.status==='pending')action=rel.requester_id===session.user.id?'Pedido enviado':'Aceitar pedido';const addOnly=action==='Adicionar Buddy';return `<article class="buddy-person" data-user="${p.id}" style="--role:${color}"><img src="${esc(avatar(p))}" alt=""><div><strong>${esc(name(p))}${adminHammer(p)}</strong><small>${label} · LVL ${Number(p.level||1)}</small><em>● ${esc(p.presence||'offline')}</em></div><button type="button" class="buddy-quick-action${addOnly?' is-add-only':''}" data-quick="${p.id}" title="${action}" aria-label="${action}"><span class="buddy-action-icon">${addOnly?'👤＋':action==='Conversar'?'💬':''}</span>${addOnly?'':`<span>${action}</span>`}</button><button class="buddy-bell" title="Notificações desligadas" aria-label="Notificações desligadas">🔕</button></article>`}
async function load(){const s=await sb.auth.getSession();session=s.data.session;if(!session){$('buddyLogin').hidden=false;return}$('buddyLogin').hidden=true;$('buddyApp').hidden=false;const [pr,rl,bl]=await Promise.all([sb.from('profiles').select('*').order('game_nickname'),sb.from('buddy_relations').select('*'),sb.from('user_blocks').select('*')]);profiles=pr.data||[];relations=rl.data||[];blocks=bl.data||[];me=profiles.find(p=>p.id===session.user.id);render();subscribePrivateRealtime();}
function visible(){const q=$('buddySearch').value.trim().toLowerCase();let rows=profiles.filter(p=>p.id!==session.user.id&&p.profile_public!==false);if(tab==='buddies')rows=rows.filter(p=>relationWith(p.id)?.status==='accepted');if(tab==='requests')rows=rows.filter(p=>{const r=relationWith(p.id);return r?.status==='pending'&&r.addressee_id===session.user.id});if(tab==='blocked')rows=profiles.filter(p=>isBlocked(p.id));if(q)rows=rows.filter(p=>name(p).toLowerCase().includes(q));return rows}
function render(){const rows=visible();$('buddyList').innerHTML=rows.length?rows.map(card).join(''):'<p class="buddy-none">Nenhum utilizador aqui.</p>';bindCards()}
function cancelPreviewClose(){clearTimeout(previewCloseTimer);previewCloseTimer=null}
function schedulePreviewClose(delay=60){cancelPreviewClose();previewCloseTimer=setTimeout(()=>hidePreview(true),delay)}
function bindCards(){document.querySelectorAll('.buddy-person').forEach(el=>{const id=el.dataset.user,triggerParts=[el.querySelector('img'),el.querySelector('div')].filter(Boolean);el.onclick=e=>{if(e.target.closest('button')||longPressOpened){longPressOpened=false;return}openProfile(id)};triggerParts.forEach(part=>{part.classList.add('buddy-preview-trigger');part.onmouseenter=()=>{cancelPreviewClose();showPreview(id,el)};part.onmouseleave=e=>{const box=$('buddyPreview');if(box&&!box.hidden&&box.contains(e.relatedTarget))return;schedulePreviewClose(60)}});el.querySelectorAll('button').forEach(button=>button.onmouseenter=()=>hidePreview(true));el.ontouchstart=e=>{if(e.target.closest('button'))return;longPressOpened=false;clearTimeout(holdTimer);holdTimer=setTimeout(()=>{longPressOpened=true;showPreview(id,el)},2000)};el.ontouchend=()=>clearTimeout(holdTimer);el.ontouchcancel=()=>clearTimeout(holdTimer)});document.querySelectorAll('[data-quick]').forEach(b=>{let touchHandled=false;const run=e=>{e.preventDefault();e.stopPropagation();hidePreview(true);quickAction(b.dataset.quick)};b.onclick=e=>{if(touchHandled){touchHandled=false;return}run(e)};b.ontouchend=e=>{touchHandled=true;run(e);setTimeout(()=>{touchHandled=false},450)}})}
function positionPreview(anchor){const box=$('buddyPreview');if(!box||box.hidden||!anchor)return;const r=anchor.getBoundingClientRect(),gap=0,width=Math.min(290,innerWidth-16);let left;if(innerWidth>=760&&r.right+gap+width<=innerWidth-8)left=r.right+gap;else left=Math.max(8,Math.min(innerWidth-width-8,r.left+16));let top=r.bottom+gap;if(top+box.offsetHeight>innerHeight-8)top=Math.max(8,r.top-box.offsetHeight-gap);box.style.width=width+'px';box.style.left=left+'px';box.style.top=top+'px'}
function showPreview(id,anchor){const p=profiles.find(x=>x.id===id);if(!p)return;cancelPreviewClose();previewAnchor=anchor;previewUserId=id;const [label,color]=roleInfo(p),box=$('buddyPreview');box.innerHTML=`<div style="--role:${color}"><img src="${esc(avatar(p))}" alt=""><h3>${esc(name(p))}${adminHammer(p)}</h3><b>${label} · LVL ${p.level||1}</b><p>${esc(p.presence||'offline')}</p><section><button data-preview-profile>Abrir perfil</button><button data-preview-add>＋</button></section></div>`;box.hidden=false;box.onmouseenter=cancelPreviewClose;box.onmouseleave=e=>{if(previewAnchor&&previewAnchor.contains(e.relatedTarget))return;hidePreview(true)};box.ontouchstart=cancelPreviewClose;positionPreview(anchor);box.querySelector('[data-preview-profile]').onclick=e=>{e.stopPropagation();openProfile(id)};box.querySelector('[data-preview-add]').onclick=e=>{e.stopPropagation();quickAction(id)}}
function hidePreview(force=false){if(!force&&previewCloseTimer)return;cancelPreviewClose();const box=$('buddyPreview');if(box)box.hidden=true;previewAnchor=null;previewUserId=null}
window.addEventListener('resize',()=>previewAnchor&&positionPreview(previewAnchor));window.addEventListener('scroll',()=>previewAnchor&&positionPreview(previewAnchor),true);document.addEventListener('pointerdown',e=>{const box=$('buddyPreview');if(!box||box.hidden)return;if(!box.contains(e.target)&&!e.target.closest('.buddy-person'))hidePreview(true)});
async function quickAction(id){if(isBlocked(id)){await sb.from('user_blocks').delete().eq('blocker_id',session.user.id).eq('blocked_id',id);return load();}const r=relationWith(id);if(!r){await sb.from('buddy_relations').insert({requester_id:session.user.id,addressee_id:id});return load()}if(r.status==='pending'&&r.addressee_id===session.user.id){await sb.from('buddy_relations').update({status:'accepted',updated_at:new Date().toISOString()}).eq('id',r.id);return load()}if(r.status==='accepted')return openChat(id);}
function openProfile(id){hidePreview();const p=profiles.find(x=>x.id===id);if(!p)return;const [label,color]=roleInfo(p);$('buddyProfileModal').innerHTML=`<div class="buddy-modal-backdrop" data-close></div><article style="--role:${color}"><button data-close>×</button><img src="${esc(avatar(p))}"><div><small>PERFIL DA COMUNIDADE</small><h2>${esc(name(p))}${adminHammer(p)}</h2><strong>${label} · LVL ${p.level||1}</strong><p>${esc(p.public_bio||'Sem biografia.')}</p><dl><div><dt>Jogo</dt><dd>${esc(p.main_game||'—')}</dd></div><div><dt>Música</dt><dd>${esc(p.favorite_music||'—')}</dd></div><div><dt>Tempo ativo</dt><dd>${Math.floor((p.active_seconds||0)/3600)}h</dd></div><div><dt>AFK</dt><dd>${Math.floor((p.afk_seconds||0)/3600)}h</dd></div></dl><footer><button data-add>Adicionar Buddy</button><button data-chat>Conversar</button><button data-block>Bloquear</button><button data-report>Reportar</button></footer></div></article>`;$('buddyProfileModal').hidden=false;$('buddyProfileModal').querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>$('buddyProfileModal').hidden=true);$('buddyProfileModal').querySelector('[data-add]').onclick=()=>quickAction(id);$('buddyProfileModal').querySelector('[data-chat]').onclick=()=>openChat(id);$('buddyProfileModal').querySelector('[data-block]').onclick=()=>blockUser(id);$('buddyProfileModal').querySelector('[data-report]').onclick=()=>reportUser(id)}
function stopMessagePolling(){clearInterval(messagePollTimer);messagePollTimer=null}
function startMessagePolling(){stopMessagePolling();messagePollTimer=setInterval(()=>{if(selected&&!document.hidden)loadMessages(false)},1800)}
function closeConversation(){selected=null;lastMessageSignature='';renderedMessageIds.clear();stopMessagePolling();$('buddyConversation').hidden=true;$('buddyEmpty').hidden=false;const app=$('buddyApp'),sidebar=app.querySelector('.buddy-sidebar'),main=app.querySelector('.buddy-main');app.classList.remove('conversation-open');sidebar.style.removeProperty('display');main.style.removeProperty('display');main.style.removeProperty('margin-top');document.body.classList.remove('buddy-mobile-chat-open');syncMobileViewport()}
async function openChat(id){selected=profiles.find(p=>p.id===id);if(!selected)return;hidePreview(true);$('buddyProfileModal').hidden=true;const app=$('buddyApp'),sidebar=app.querySelector('.buddy-sidebar'),main=app.querySelector('.buddy-main');$('buddyEmpty').hidden=true;$('buddyConversation').hidden=false;app.classList.add('conversation-open');if(innerWidth<=760){sidebar.style.display='none';main.style.display='block';main.style.marginTop='0';document.body.classList.add('buddy-mobile-chat-open');syncMobileViewport();window.scrollTo({top:0,left:0,behavior:'auto'})}const [label,color]=roleInfo(selected);$('buddyChatHead').innerHTML=`<button class="buddy-chat-back" data-back aria-label="Voltar à lista">←</button><img src="${esc(avatar(selected))}"><div><strong style="color:${color}">${esc(name(selected))}${adminHammer(selected)}</strong><small>${label} · ${esc(selected.presence||'offline')}</small></div><button class="buddy-group-add" data-group title="Adicionar pessoas à conversa (em breve)">👥＋</button><button data-profile>Perfil</button><button data-block>Bloquear</button><button data-delete>Apagar</button>`;$('buddyChatHead').querySelector('[data-back]').onclick=closeConversation;$('buddyChatHead').querySelector('[data-group]').onclick=()=>alert('Conversas em grupo chegam no próximo passo. Limite inicial: 6 pessoas.');$('buddyChatHead').querySelector('[data-profile]').onclick=()=>openProfile(id);$('buddyChatHead').querySelector('[data-block]').onclick=()=>blockUser(id);$('buddyChatHead').querySelector('[data-delete]').onclick=deleteConversation;await loadMessages(true);startMessagePolling();requestAnimationFrame(()=>{const box=$('buddyMessages');if(box)box.scrollTop=box.scrollHeight})}
function messageBelongsToOpenChat(m){return !!(selected&&session&&[m.sender_id,m.receiver_id].includes(session.user.id)&&[m.sender_id,m.receiver_id].includes(selected.id))}
function messageMarkup(m){return `<p data-message-id="${esc(m.id)}" class="${m.sender_id===session.user.id?'mine':'theirs'}">${esc(m.body)}<small>${new Date(m.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></p>`}
function appendRealtimeMessage(m){if(!messageBelongsToOpenChat(m)||renderedMessageIds.has(String(m.id)))return;const hidden=m.sender_id===session.user.id?m.hidden_by_sender:m.hidden_by_receiver;if(hidden)return;const box=$('buddyMessages'),wasNearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<120;box.insertAdjacentHTML('beforeend',messageMarkup(m));renderedMessageIds.add(String(m.id));if(wasNearBottom||m.sender_id===session.user.id)box.scrollTop=box.scrollHeight;if(m.receiver_id===session.user.id)markOpenConversationRead()}
async function markOpenConversationRead(){if(!selected)return;await sb.from('private_messages').update({read_at:new Date().toISOString()}).eq('receiver_id',session.user.id).eq('sender_id',selected.id).is('read_at',null);window.dispatchEvent(new Event('buddy:messages-read'))}
async function loadMessages(force=false){if(!selected)return;const selectedId=selected.id;const {data,error}=await sb.from('private_messages').select('*').or(`and(sender_id.eq.${session.user.id},receiver_id.eq.${selectedId}),and(sender_id.eq.${selectedId},receiver_id.eq.${session.user.id})`).order('created_at');if(error||!selected||selected.id!==selectedId)return;const visible=(data||[]).filter(m=>!(m.sender_id===session.user.id?m.hidden_by_sender:m.hidden_by_receiver));const signature=visible.map(m=>`${m.id}:${m.created_at}:${m.hidden_by_sender}:${m.hidden_by_receiver}`).join('|');if(!force&&signature===lastMessageSignature)return;lastMessageSignature=signature;const box=$('buddyMessages'),wasNearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<90;renderedMessageIds=new Set(visible.map(m=>String(m.id)));box.innerHTML=visible.map(messageMarkup).join('');if(force||wasNearBottom)box.scrollTop=box.scrollHeight;await markOpenConversationRead()}
$('buddyMessageForm').onsubmit=async e=>{e.preventDefault();const input=$('buddyMessageInput'),body=input.value.trim();if(!body||!selected)return;const receiverId=selected.id,inputBody=body;input.value='';const {error}=await sb.from('private_messages').insert({sender_id:session.user.id,receiver_id:receiverId,body:inputBody});if(error){input.value=inputBody;return alert(error.message)}await loadMessages(true)};
async function blockUser(id){if(!confirm('Bloquear este utilizador?'))return;await sb.from('user_blocks').upsert({blocker_id:session.user.id,blocked_id:id});const r=relationWith(id);if(r)await sb.from('buddy_relations').delete().eq('id',r.id);$('buddyProfileModal').hidden=true;closeConversation();load()}
async function deleteConversation(){if(!selected||!confirm('Apagar esta conversa apenas para ti?'))return;const {data}=await sb.from('private_messages').select('id,sender_id,receiver_id').or(`and(sender_id.eq.${session.user.id},receiver_id.eq.${selected.id}),and(sender_id.eq.${selected.id},receiver_id.eq.${session.user.id})`);for(const m of data||[])await sb.from('private_messages').update(m.sender_id===session.user.id?{hidden_by_sender:true}:{hidden_by_receiver:true}).eq('id',m.id);loadMessages()}
function reportUser(id){const p=profiles.find(x=>x.id===id),box=$('buddyReportModal');box.innerHTML=`<div class="buddy-modal-backdrop" data-close></div><form><button type="button" data-close>×</button><h3>Reportar ${esc(name(p))}</h3><select required><option value="">Motivo</option><option value="assedio">Assédio</option><option value="spam">Spam</option><option value="ameaca">Ameaça</option><option value="conteudo_improprio">Conteúdo impróprio</option><option value="perfil_falso">Perfil falso</option><option value="outro">Outro</option></select><textarea maxlength="1000" placeholder="Detalhes opcionais"></textarea><button>Enviar denúncia</button></form>`;box.hidden=false;box.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>box.hidden=true);box.querySelector('form').onsubmit=async e=>{e.preventDefault();await sb.from('user_reports').insert({reporter_id:session.user.id,reported_id:id,reason:e.target.querySelector('select').value,details:e.target.querySelector('textarea').value.trim()||null});box.hidden=true;alert('Denúncia enviada.')}}
function subscribePrivateRealtime(){if(!session)return;if(privateChannel)sb.removeChannel(privateChannel);privateChannel=sb.channel(`buddy-private-${session.user.id}-${Date.now()}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'private_messages'},payload=>{const row=payload.new||{};appendRealtimeMessage(row);setTimeout(()=>messageBelongsToOpenChat(row)&&loadMessages(false),180)}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'private_messages'},payload=>{const row=payload.new||payload.old||{};if(messageBelongsToOpenChat(row))loadMessages(true)}).subscribe(status=>{if(status==='SUBSCRIBED'){if(selected)loadMessages(false)}else if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'||status==='CLOSED'){startMessagePolling()}})}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{if(innerWidth<=760&&selected)closeConversation();tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));render()});$('buddySearch').oninput=render;document.addEventListener('visibilitychange',()=>{if(!document.hidden&&selected)loadMessages(true)});window.addEventListener('focus',()=>selected&&loadMessages(true));window.addEventListener('online',()=>{subscribePrivateRealtime();if(selected)loadMessages(true)});window.TeamBuddy={isConversationOpenWith:id=>!!(selected&&selected.id===id),openChat};(async()=>{await load();const id=new URLSearchParams(location.search).get('chat');if(id&&profiles.some(p=>p.id===id))openChat(id)})();})();
