(() => {
'use strict';
if(window.TeamProfileV120)return;window.TeamProfileV120=true;
const root=document.getElementById('profileRoot'),sb=window.teamSupabase;if(!root||!sb)return;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=v=>String(v??'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const I={game:'<svg viewBox="0 0 24 24"><path d="M8 8h8a5 5 0 0 1 4.7 6.7l-1 2.8a2.2 2.2 0 0 1-3.7.8L14.5 17h-5L8 18.3a2.2 2.2 0 0 1-3.7-.8l-1-2.8A5 5 0 0 1 8 8Z"/><path d="M7 12v4M5 14h4M16 12h.01M18 15h.01"/></svg>',network:'<svg viewBox="0 0 24 24"><circle cx="6" cy="12" r="2.4"/><circle cx="17" cy="5" r="2.4"/><circle cx="18" cy="18" r="2.4"/><path d="m8.2 10.8 6.6-4.5M8.3 13.1l7.3 3.7"/></svg>',profile:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></svg>',actions:'<svg viewBox="0 0 24 24"><circle cx="5" cy="12" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="19" cy="12" r="1.5"/></svg>',friend:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3 20a6 6 0 0 1 12 0M16 6a3 3 0 0 1 0 6M17 15a5 5 0 0 1 4 5"/></svg>',message:'<svg viewBox="0 0 24 24"><path d="M20 14a4 4 0 0 1-4 4H9l-5 3V7a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4Z"/><path d="M8 9h8M8 13h5"/></svg>',report:'<svg viewBox="0 0 24 24"><path d="M5 21V4m0 1h11l-2 4 2 4H5"/></svg>',block:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg>',edit:'<svg viewBox="0 0 24 24"><path d="m4 20 4-1 10-10-3-3L5 16l-1 4Z"/></svg>',crown:'<svg viewBox="0 0 24 24"><path d="m3 7 4 4 5-7 5 7 4-4-2 11H5L3 7Z"/><path d="M5 21h14"/></svg>',code:'<svg viewBox="0 0 24 24"><path d="m8 8-4 4 4 4M16 8l4 4-4 4M14 5l-4 14"/></svg>',shield:'<svg viewBox="0 0 24 24"><path d="M12 3 20 6v6c0 5-3.4 8-8 9-4.6-1-8-4-8-9V6l8-3Z"/></svg>',stream:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="2"/><path d="M8.5 8.5a5 5 0 0 0 0 7M15.5 8.5a5 5 0 0 1 0 7M5.5 5.5a9 9 0 0 0 0 13M18.5 5.5a9 9 0 0 1 0 13"/></svg>'};
const profileCovers={cover_gold:'assets/profile-covers/cover-gold.png',cover_green_black:'assets/profile-covers/cover-green-black.png',cover_neon:'assets/profile-covers/cover-neon.png',cover_lambretta_classic:'assets/profile-covers/cover-lambretta-classic.png',cover_competitive:'assets/profile-covers/cover-competitive.png',cover_cyber_gamer:'assets/profile-covers/cover-cyber-gamer.png',cover_minimal:'assets/profile-covers/cover-minimal.png'};
const roleMeta={boss:['BOSS','#ffd700','crown'],administrator:['ADMINISTRADOR','#ff2d55','shield'],developer:['DESENVOLVEDOR','#00e6ff','code'],moderator:['MODERADOR','#207bff','shield'],staff:['STAFF','#75b8ff','shield'],streamer:['STREAMER','#b64dff','stream'],supporter:['APOIADOR','#32ff7e','stream'],vip:['VIP','#ff8a00','crown'],member:['MEMBRO','#f4f7fa','profile']};
const avatarUrl=p=>window.TeamProfiles?.getAvatarUrl?.(p)||p?.avatar_display_url||p?.avatar_external_url||p?.custom_avatar_url||p?.avatar_url||'';
function avatar(p){const src=avatarUrl(p);return src?`<img src="${esc(src)}" alt="" decoding="async">`:`<span>${esc((p?.display_name||p?.game_nickname||p?.full_name||'TL').slice(0,2).toUpperCase())}</span>`}
const presence=p=>window.TeamPresence?.resolve?.(p)||'offline';
const presenceLabel=s=>({online:'ONLINE',busy:'OCUPADO',away:'AUSENTE',offline:'OFFLINE'}[s]||'OFFLINE');
function roles(p){let rows=[];try{rows=window.TeamPermissions?.getVisualRoles?.(p)||[]}catch{}if(!rows.length)rows=[{key:p?.role||'member'}];return rows.slice(0,3).map(r=>{const key=String(r?.key||'member').toLowerCase(),m=roleMeta[key]||roleMeta.member;return `<span class="p120-role" style="--role:${m[1]}"><i>${I[m[2]]}</i><b>${m[0]}</b></span>`}).join('')}
function games(p,catalog){const map=new Map((catalog?.games||[]).map(g=>[g.slug,g]));const chosen=(Array.isArray(p.games)&&p.games.length?p.games:[p.main_game].filter(Boolean)).slice(0,4);const rows=chosen.map(slug=>{const g=map.get(slug)||{slug,name:String(slug||'Jogo').replace(/[-_]/g,' ').replace(/\b\w/g,c=>c.toUpperCase())};return `<article class="p120-game"><div class="p120-game-media"><img src="assets/game-covers/${encodeURIComponent(slug)}.webp" alt="Capa de ${esc(g.name)}" decoding="async" loading="lazy"><span>${esc(g.short_name||g.name||slug)}</span></div><b>${esc(g.name||slug)}</b></article>`});while(rows.length<4)rows.push('<article class="p120-game is-empty"><div class="p120-game-media"><span>—</span></div><b>Sem jogo</b></article>');return rows.join('')}
function bindGameImages(){qa('.p120-game-media img',root).forEach(img=>{const ok=()=>img.classList.add('is-loaded');if(img.complete&&img.naturalWidth)ok();else img.addEventListener('load',ok,{once:true});img.addEventListener('error',()=>img.remove(),{once:true})})}
async function friendsFor(userId){try{const [l,c]=await Promise.all([sb.rpc('tl_profile_public_friends',{p_user_id:userId,p_limit:8}),sb.rpc('tl_profile_public_friend_count',{p_user_id:userId})]);if(l.error||c.error)return{list:[],total:0};return{list:l.data||[],total:Number(c.data||0)}}catch{return{list:[],total:0}}}
function friendStrip(friends){if(!friends.list.length)return '<div class="p120-friends-empty">Ainda não há amigos para mostrar.</div>';return `<div class="p120-friends-track">${friends.list.map(f=>{const st=presence(f);return `<a class="p120-friend" data-user-id="${esc(f.id)}" href="profile.html?user=${encodeURIComponent(f.id)}"><span class="p120-friend-avatar">${avatar(f)}<i class="is-${esc(st)}"></i></span><strong>${esc(f.display_name||f.game_nickname||f.full_name||'Membro')}</strong></a>`}).join('')}${friends.total>friends.list.length?`<span class="p120-friend-more"><b>+${friends.total-friends.list.length}</b><small>amigos</small></span>`:''}</div>`}
function socialItems(p){const out={discord:{label:'Discord',value:String(p.discord||''),url:''},tiktok:{label:'TikTok',value:'',url:''},youtube:{label:'YouTube',value:'',url:''},twitch:{label:'Twitch',value:'',url:''}};const raw=p?.social_links;const rows=Array.isArray(raw)?raw:(raw&&typeof raw==='object'?Object.entries(raw).map(([type,v])=>typeof v==='object'?{type,...v}:{type,url:v}):[]);rows.forEach(r=>{const type=String(r?.type||r?.platform||'').toLowerCase().replace(/[^a-z]/g,'');if(!out[type])return;out[type].url=String(r.url||r.href||'').trim();out[type].value=String(r.handle||r.username||'').trim()});return Object.entries(out).map(([type,v])=>({type,...v}))}
function socialSection(p){return `<div class="p120-social-grid">${socialItems(p).map(x=>{const val=x.value||x.url||'Não informado';return `<article class="p120-social"><strong>${esc(x.label)}</strong><small>${esc(val)}</small></article>`}).join('')}</div>`}
function quickFacts(p,stats){const c=window.TeamCountryCatalog?.resolve?.(p.country),country=c?`${c.flag||''} ${c.name}`.trim():(p.country||'—'),since=stats?.memberSince?new Date(stats.memberSince).toLocaleDateString('pt-PT'):(p.created_at?new Date(p.created_at).toLocaleDateString('pt-PT'):'—');return `<section class="p120-facts"><article><small>PAÍS</small><strong>${esc(country)}</strong></article><article><small>NICKNAME</small><strong>${esc(p.game_nickname_public||p.game_nickname||'—')}</strong></article><article><small>MEMBRO DESDE</small><strong>${esc(since)}</strong></article><article><small>TÓPICOS</small><strong>${Number(stats?.topics||0)}</strong></article><article><small>RESPOSTAS</small><strong>${Number(stats?.replies||0)}</strong></article></section>`}
function info(p,stats,own){return `${quickFacts(p,stats)}${own?`<a class="p120-edit" href="profile-edit.html">${I.edit}<span>Editar perfil</span></a>`:''}`}
async function relationFor(viewer,user){if(viewer===user)return{state:'self'};const pair=`and(requester_id.eq.${viewer},addressee_id.eq.${user}),and(requester_id.eq.${user},addressee_id.eq.${viewer})`;const [rel,blocks]=await Promise.all([sb.from('buddy_relations').select('*').or(pair).maybeSingle(),sb.from('user_blocks').select('*').or(`and(blocker_id.eq.${viewer},blocked_id.eq.${user}),and(blocker_id.eq.${user},blocked_id.eq.${viewer})`)]);if(rel.error)throw rel.error;if(blocks.error)throw blocks.error;const mine=(blocks.data||[]).some(x=>x.blocker_id===viewer),theirs=(blocks.data||[]).some(x=>x.blocker_id===user);if(mine)return{state:'blocked',relation:rel.data};if(theirs)return{state:'blocked-by',relation:rel.data};if(rel.data?.status==='accepted')return{state:'buddy',relation:rel.data};if(rel.data?.status==='pending'&&rel.data.requester_id===viewer)return{state:'sent',relation:rel.data};if(rel.data?.status==='pending')return{state:'received',relation:rel.data};return{state:'none',relation:rel.data}}
function actions(rel,userId){if(rel.state==='blocked-by')return'<p class="p120-muted">Este perfil não está disponível para interação.</p>';if(rel.state==='blocked')return`<div class="p120-actions"><button data-action="unblock">${I.block}<span>Desbloquear</span></button></div>`;const report=`<button data-action="report">${I.report}<span>Denunciar</span></button>`,block=`<button class="is-danger" data-action="block">${I.block}<span>Bloquear</span></button>`;if(rel.state==='buddy')return`<div class="p120-actions"><a class="is-primary" href="buddy.html?user=${encodeURIComponent(userId)}">${I.message}<span>Mensagem</span></a><button data-action="unfriend">${I.friend}<span>Desfazer amizade</span></button>${report}${block}</div>`;if(rel.state==='received')return`<div class="p120-actions"><button class="is-primary" data-action="accept">${I.friend}<span>Aceitar amizade</span></button><button data-action="reject">${I.friend}<span>Recusar</span></button>${report}${block}</div>`;const friend=rel.state==='sent'?`<button disabled>${I.friend}<span>Pedido enviado</span></button>`:`<button class="is-primary" data-action="add">${I.friend}<span>Adicionar amigo</span></button>`;return`<div class="p120-actions">${friend}<a href="buddy.html?user=${encodeURIComponent(userId)}&request=1">${I.message}<span>Enviar mensagem</span></a>${report}${block}</div>`}
function bindTabs(){qa('[data-tab]',root).forEach(b=>b.addEventListener('click',()=>{qa('[data-tab]',root).forEach(x=>x.classList.toggle('is-active',x===b));qa('[data-panel]',root).forEach(x=>x.hidden=x.dataset.panel!==b.dataset.tab)}))}
async function bindActions(service,rel,userId){qa('[data-action]',root).forEach(btn=>btn.addEventListener('click',async()=>{const a=btn.dataset.action;try{if(a==='add')await service.request(userId);if(a==='accept')await service.respond(rel.relation.id,true);if(a==='reject')await service.respond(rel.relation.id,false);if(a==='unfriend'){const pair=`and(requester_id.eq.${service.userId},addressee_id.eq.${userId}),and(requester_id.eq.${userId},addressee_id.eq.${service.userId})`;const r=await sb.from('buddy_relations').delete().or(pair);if(r.error)throw r.error}if(a==='block')await service.block(userId);if(a==='unblock')await service.unblock(userId);if(a==='report'){await service.report(userId,'profile','Denúncia enviada pelo perfil.')}await renderAll()}catch(e){console.error('[Profile V120 action]',e)}}))}
function syncRenderedPresence(){qa('.p120-friend[data-user-id]',root).forEach(item=>{const st=presence(item.dataset.userId),dot=q('.p120-friend-avatar i',item);if(dot)dot.className=`is-${st}`});const hero=q('.p120-hero[data-user-id]',root);if(hero){const st=presence(hero.dataset.userId),dot=q('.p120-avatar i',hero),label=q('.p120-presence',hero);if(dot)dot.className=`is-${st}`;if(label){label.className=`p120-presence is-${st}`;label.innerHTML=`<i></i>${esc(presenceLabel(st))}`}}}
async function renderAll(){const session=await window.TeamAuth?.getSession?.();if(!session?.user){root.innerHTML='<section class="p120-state"><h1>Perfil Team Lambreta</h1><p>Inicia sessão para veres os perfis.</p></section>';return}const userId=new URLSearchParams(location.search).get('user')||session.user.id,own=userId===session.user.id,service=new window.TeamBuddyFriendsService(sb,session.user.id);const [p,stats,catalog,rel,friends]=await Promise.all([window.TeamProfiles.getPublicProfile(userId,{fresh:true}),window.TeamProfiles.getProfileStats(userId),window.TeamProfiles.getCatalog(),relationFor(session.user.id,userId),friendsFor(userId)]);if(!p)throw new Error('Perfil não encontrado.');const st=presence(p),cover=profileCovers[p.cover_preset]||profileCovers.cover_cyber_gamer,bio=text(p.bio||p.public_bio||'Jogo as vezes para passar tempo..');const tabs=[['games',I.game,'JOGOS'],['social',I.network,'REDES'],['profile',I.profile,'PERFIL']];if(!own)tabs.push(['actions',I.actions,'AÇÕES']);root.innerHTML=`<section class="p120-hero" data-user-id="${esc(userId)}" style="--cover:url('${esc(cover)}')"><div class="p120-avatar">${avatar(p)}<i class="is-${esc(st)}"></i></div><div class="p120-identity"><h1>${esc(text(p.display_name||p.game_nickname||'Membro Lambreta'))}</h1><div class="p120-presence is-${esc(st)}"><i></i>${esc(presenceLabel(st))}</div><div class="p120-roles">${roles(p)}</div><p>${esc(bio)}</p></div></section>${quickFacts(p,stats)}<section class="p120-friends"><header><span>${I.friend}</span><strong>AMIGOS</strong><small>${friends.total}</small></header>${friendStrip(friends)}</section><section class="p120-card"><nav class="p120-tabs ${own?'is-own':'is-public'}">${tabs.map((t,i)=>`<button type="button" data-tab="${t[0]}" class="${i===0?'is-active':''}">${t[1]}<strong>${t[2]}</strong></button>`).join('')}</nav><div class="p120-panels"><section data-panel="games"><h2>${I.game} JOGOS MAIS JOGADOS</h2><div class="p120-games">${games(p,catalog)}</div></section><section data-panel="social" hidden><h2>${I.network} REDES SOCIAIS</h2>${socialSection(p)}</section><section data-panel="profile" hidden><h2>${I.profile} INFORMAÇÕES</h2>${info(p,stats,own)}</section>${own?'':`<section data-panel="actions" hidden><h2>${I.actions} AÇÕES</h2>${actions(rel,userId)}</section>`}</div></section>`;bindTabs();bindGameImages();if(!own)await bindActions(service,rel,userId)}
window.addEventListener('tl:presence-peers',syncRenderedPresence);
renderAll().catch(e=>{console.error('[Profile V120]',e);root.innerHTML=`<section class="p120-state"><h1>Perfil indisponível</h1><p>${esc(e?.message||'Não foi possível carregar o perfil.')}</p></section>`});
})();