(() => {
'use strict';
if(window.TeamProfileV119)return;window.TeamProfileV119=true;
const root=document.getElementById('profileRoot'),sb=window.teamSupabase;if(!root||!sb)return;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=v=>String(v??'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const I={game:'<svg viewBox="0 0 24 24"><path d="M8 8h8a5 5 0 0 1 4.7 6.7l-1 2.8a2.2 2.2 0 0 1-3.7.8L14.5 17h-5L8 18.3a2.2 2.2 0 0 1-3.7-.8l-1-2.8A5 5 0 0 1 8 8Z"/><path d="M7 12v4M5 14h4M16 12h.01M18 15h.01"/></svg>',network:'<svg viewBox="0 0 24 24"><circle cx="6" cy="12" r="2.4"/><circle cx="17" cy="5" r="2.4"/><circle cx="18" cy="18" r="2.4"/><path d="m8.2 10.8 6.6-4.5M8.3 13.1l7.3 3.7"/></svg>',profile:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></svg>',actions:'<svg viewBox="0 0 24 24"><circle cx="5" cy="12" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="19" cy="12" r="1.5"/></svg>',friend:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3 20a6 6 0 0 1 12 0M16 6a3 3 0 0 1 0 6M17 15a5 5 0 0 1 4 5"/></svg>',message:'<svg viewBox="0 0 24 24"><path d="M20 14a4 4 0 0 1-4 4H9l-5 3V7a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4Z"/><path d="M8 9h8M8 13h5"/></svg>',report:'<svg viewBox="0 0 24 24"><path d="M5 21V4m0 1h11l-2 4 2 4H5"/></svg>',block:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></svg>',edit:'<svg viewBox="0 0 24 24"><path d="m4 20 4-1 10-10-3-3L5 16l-1 4Z"/></svg>',discord:'<svg viewBox="0 0 24 24"><path d="M8 7a14 14 0 0 1 8 0l2 3 1 7a15 15 0 0 1-4 2l-1-2a9 9 0 0 1-4 0l-1 2a15 15 0 0 1-4-2l1-7 2-3Z"/><circle cx="9.5" cy="12.5" r="1"/><circle cx="14.5" cy="12.5" r="1"/></svg>',tiktok:'<svg viewBox="0 0 24 24"><path d="M15 4c.4 2.3 1.8 3.7 4 4v3c-1.6 0-2.9-.4-4-1.2v5.7A5.5 5.5 0 1 1 10 10v3.1a2.5 2.5 0 1 0 2 2.4V4z"/></svg>',youtube:'<svg viewBox="0 0 24 24"><path d="M21 12s0-4-1-5-3-1-8-1-7 0-8 1-1 5 0 10c1 1 8 1 8 1s7 0 8-1c1-1 1-5 1-5Z"/><path d="m10 9 5 3-5 3Z"/></svg>',twitch:'<svg viewBox="0 0 24 24"><path d="M5 3h16v11l-5 5h-4l-3 3v-3H4V6Z"/><path d="M12 8v4M16 8v4"/></svg>'};
const profileCovers={cover_gold:'assets/profile-covers/cover-gold.png',cover_green_black:'assets/profile-covers/cover-green-black.png',cover_neon:'assets/profile-covers/cover-neon.png',cover_lambretta_classic:'assets/profile-covers/cover-lambretta-classic.png',cover_competitive:'assets/profile-covers/cover-competitive.png',cover_cyber_gamer:'assets/profile-covers/cover-cyber-gamer.png',cover_minimal:'assets/profile-covers/cover-minimal.png'};
const steam={'counter-strike-2':'730','grand-theft-auto-v':'271590','dota-2':'570','apex-legends':'1172470','dead-by-daylight':'381210','marvel-rivals':'2767030','path-of-exile-2':'2694490','rust':'252490','rocket-league':'252950','pubg-battlegrounds':'578080','the-finals':'2073850','destiny-2':'1085660','warframe':'230410','elden-ring':'1245620','cyberpunk-2077':'1091500','red-dead-redemption-2':'1174180','street-fighter-6':'1364780','tekken-8':'1778820','dayz':'221100','terraria':'105600','stardew-valley':'413150','the-sims-4':'1222670','no-mans-sky':'275850','sea-of-thieves':'1172620','helldivers-2':'553850','war-thunder':'236390','fall-guys':'1097150','among-us':'945360','phasmophobia':'739630','lethal-company':'1966720','content-warning':'2881650','garrys-mod':'4000','geometry-dash':'322170','old-school-runescape':'1343370','albion-online':'761890','smite-2':'2437170','delta-force':'2507950','trackmania':'2225070','path-of-exile':'238960','balatro':'2379780','halo-infinite':'1240440'};
const special={minecraft:'https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/key-art/Minecraft_KeyArt_2024.jpg',fortnite:'https://cdn2.unrealengine.com/fortnite-og-image-1920x1080-5e359e3cc6f7.jpg'};
const coverFor=slug=>special[slug]||(steam[slug]?`https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/${steam[slug]}/header.jpg`:'');
const avatarUrl=p=>window.TeamProfiles?.getAvatarUrl?.(p)||p?.avatar_display_url||p?.avatar_external_url||p?.custom_avatar_url||p?.avatar_url||'';
const avatar=p=>avatarUrl(p)?`<img src="${esc(avatarUrl(p))}" alt="" decoding="async">`:`<span>${esc((p?.display_name||p?.game_nickname||p?.full_name||'TL').slice(0,2).toUpperCase())}</span>`;
const presence=p=>window.TeamPresence?.resolve?.(p)||'offline';
const presenceLabel=s=>({online:'ONLINE',busy:'OCUPADO',away:'AUSENTE',offline:'OFFLINE'}[s]||'OFFLINE');
const roleMeta={boss:['BOSS','#ffd700'],administrator:['ADMINISTRADOR','#ff2d55'],developer:['DESENVOLVEDOR','#00e6ff'],moderator:['MODERADOR','#207bff'],staff:['STAFF','#75b8ff'],streamer:['STREAMER','#b64dff'],supporter:['APOIADOR','#32ff7e'],vip:['VIP','#ff8a00'],member:['MEMBRO','#f4f7fa']};
function roles(p){let rows=[];try{rows=window.TeamPermissions?.getVisualRoles?.(p)||[]}catch{}if(!rows.length)rows=[{key:p?.role||'member'}];return rows.slice(0,3).map(r=>{const key=String(r?.key||'member').toLowerCase();const meta=roleMeta[key]||roleMeta.member;return `<span class="p119-role" style="--role:${meta[1]}"><i>◆</i><b>${meta[0]}</b></span>`}).join('')}
function games(p,catalog){const map=new Map((catalog?.games||[]).map(g=>[g.slug,g]));const chosen=(Array.isArray(p.games)&&p.games.length?p.games:[p.main_game].filter(Boolean)).slice(0,4);const rows=chosen.map(slug=>{const g=map.get(slug)||{slug,name:String(slug||'Jogo').replace(/[-_]/g,' ').replace(/\b\w/g,c=>c.toUpperCase())};const src=coverFor(slug);return `<article class="p119-game"><div class="p119-game-media">${src?`<img src="${esc(src)}" alt="Capa de ${esc(g.name)}" decoding="async" loading="lazy"><span>${esc(g.short_name||g.name||slug)}</span>`:`<span>${esc(g.short_name||g.name||slug)}</span>`}</div><b>${esc(g.name||slug)}</b></article>`});while(rows.length<4)rows.push('<article class="p119-game is-empty"><div class="p119-game-media"><span>—</span></div><b>Sem jogo</b></article>');return rows.join('')}
function bindGameImages(){qa('.p119-game-media img',root).forEach(img=>{const ok=()=>img.classList.add('is-loaded');if(img.complete&&img.naturalWidth)ok();else img.addEventListener('load',ok,{once:true});img.addEventListener('error',()=>img.remove(),{once:true})})}
function socialItems(p){const out={discord:{label:'Discord',value:String(p.discord||''),url:''},tiktok:{label:'TikTok',value:'',url:''},youtube:{label:'YouTube',value:'',url:''},twitch:{label:'Twitch',value:'',url:''}};const raw=p?.social_links;const rows=Array.isArray(raw)?raw:(raw&&typeof raw==='object'?Object.entries(raw).map(([type,v])=>typeof v==='object'?{type,...v}:{type,url:v}):[]);rows.forEach(r=>{const type=String(r?.type||r?.platform||'').toLowerCase().replace(/[^a-z]/g,'');if(!out[type])return;out[type].url=String(r.url||r.href||'').trim();out[type].value=String(r.handle||r.username||'').trim()});return Object.entries(out).map(([type,v])=>({type,...v}))}
function socialSection(p){return `<div class="p119-social-grid">${socialItems(p).map(x=>{const val=x.value||x.url||'Não informado',body=`<span class="p119-social-icon">${I[x.type]||I.network}</span><span><strong>${esc(x.label)}</strong><small>${esc(val)}</small></span>`;return x.url?`<a class="p119-social" href="${esc(x.url)}" target="_blank" rel="noopener">${body}</a>`:`<article class="p119-social is-empty">${body}</article>`}).join('')}</div>`}
async function relationFor(viewer,user){if(viewer===user)return{state:'self'};const pair=`and(requester_id.eq.${viewer},addressee_id.eq.${user}),and(requester_id.eq.${user},addressee_id.eq.${viewer})`;const [rel,blocks]=await Promise.all([sb.from('buddy_relations').select('*').or(pair).maybeSingle(),sb.from('user_blocks').select('*').or(`and(blocker_id.eq.${viewer},blocked_id.eq.${user}),and(blocker_id.eq.${user},blocked_id.eq.${viewer})`)]);if(rel.error)throw rel.error;if(blocks.error)throw blocks.error;const mine=(blocks.data||[]).some(x=>x.blocker_id===viewer),theirs=(blocks.data||[]).some(x=>x.blocker_id===user);if(mine)return{state:'blocked',relation:rel.data};if(theirs)return{state:'blocked-by',relation:rel.data};if(rel.data?.status==='accepted')return{state:'buddy',relation:rel.data};if(rel.data?.status==='pending'&&rel.data.requester_id===viewer)return{state:'sent',relation:rel.data};if(rel.data?.status==='pending')return{state:'received',relation:rel.data};return{state:'none',relation:rel.data}}
function actions(rel,userId){if(rel.state==='blocked-by')return'<p class="p119-muted">Este perfil não está disponível para interação.</p>';if(rel.state==='blocked')return`<div class="p119-actions"><button data-action="unblock">${I.block}<span>Desbloquear</span></button></div>`;const report=`<button data-action="report">${I.report}<span>Denunciar</span></button>`,block=`<button class="is-danger" data-action="block">${I.block}<span>Bloquear</span></button>`;if(rel.state==='buddy')return`<div class="p119-actions"><a class="is-primary" href="buddy.html?user=${encodeURIComponent(userId)}">${I.message}<span>Mensagem</span></a><button data-action="unfriend">${I.friend}<span>Desfazer amizade</span></button>${report}${block}</div>`;if(rel.state==='received')return`<div class="p119-actions"><button class="is-primary" data-action="accept">${I.friend}<span>Aceitar amizade</span></button><button data-action="reject">${I.friend}<span>Recusar</span></button>${report}${block}</div>`;const friend=rel.state==='sent'?`<button disabled>${I.friend}<span>Pedido enviado</span></button>`:`<button class="is-primary" data-action="add">${I.friend}<span>Adicionar amigo</span></button>`;return`<div class="p119-actions">${friend}<a href="buddy.html?user=${encodeURIComponent(userId)}&request=1">${I.message}<span>Enviar mensagem</span></a>${report}${block}</div>`}
function info(p,stats,own){const c=window.TeamCountryCatalog?.resolve?.(p.country),country=c?`${c.flag||''} ${c.name}`.trim():(p.country||'—'),since=stats?.memberSince?new Date(stats.memberSince).toLocaleDateString('pt-PT'):(p.created_at?new Date(p.created_at).toLocaleDateString('pt-PT'):'—');return`<div class="p119-info-grid"><article><small>País</small><strong>${esc(country)}</strong></article><article><small>Nickname gamer</small><strong>${esc(p.game_nickname_public||p.game_nickname||'—')}</strong></article><article><small>Membro desde</small><strong>${esc(since)}</strong></article><article><small>Tópicos</small><strong>${Number(stats?.topics||0)}</strong></article><article><small>Respostas</small><strong>${Number(stats?.replies||0)}</strong></article><article><small>Nível</small><strong>${Number(stats?.level||0)}</strong></article></div>${own?`<a class="p119-edit" href="profile-edit.html">${I.edit}<span>Editar perfil</span></a>`:''}`}
function bindTabs(){qa('[data-tab]',root).forEach(b=>b.addEventListener('click',()=>{qa('[data-tab]',root).forEach(x=>x.classList.toggle('is-active',x===b));qa('[data-panel]',root).forEach(x=>x.hidden=x.dataset.panel!==b.dataset.tab)}))}
async function bindActions(service,rel,userId){qa('[data-action]',root).forEach(btn=>btn.addEventListener('click',async()=>{const a=btn.dataset.action;try{if(a==='add')await service.request(userId);if(a==='accept')await service.respond(rel.relation.id,true);if(a==='reject')await service.respond(rel.relation.id,false);if(a==='unfriend'){if(!confirm('Desfazer amizade?'))return;const pair=`and(requester_id.eq.${service.userId},addressee_id.eq.${userId}),and(requester_id.eq.${userId},addressee_id.eq.${service.userId})`;const r=await sb.from('buddy_relations').delete().or(pair);if(r.error)throw r.error}if(a==='block'){if(!confirm('Bloquear este utilizador?'))return;await service.block(userId)}if(a==='unblock')await service.unblock(userId);if(a==='report'){const details=prompt('Motivo da denúncia:','');if(details===null)return;await service.report(userId,'other',details)}await render()}catch(e){console.error('[Profile V119 action]',e);alert(e?.message||'Não foi possível concluir a ação.') }}))}
async function render(){const session=await window.TeamAuth?.getSession?.();if(!session?.user){root.innerHTML='<section class="p119-state"><h1>Perfil Team Lambreta</h1><p>Inicia sessão para veres os perfis.</p></section>';return}const userId=new URLSearchParams(location.search).get('user')||session.user.id,own=userId===session.user.id;const service=new window.TeamBuddyFriendsService(sb,session.user.id);const [p,stats,catalog,rel]=await Promise.all([window.TeamProfiles.getPublicProfile(userId,{fresh:true}),window.TeamProfiles.getProfileStats(userId),window.TeamProfiles.getCatalog(),relationFor(session.user.id,userId)]);if(!p)throw new Error('Perfil não encontrado.');const st=presence(p),cover=profileCovers[p.cover_preset]||profileCovers.cover_cyber_gamer;let bio=text(p.bio||p.public_bio||'Fé, foco e muita força. Unidos somos imbatíveis.');if(/svg|viewbox|path d=/i.test(bio))bio='Fé, foco e muita força. Unidos somos imbatíveis.';const tabs=[['games',I.game,'JOGOS'],['social',I.network,'REDES'],['profile',I.profile,'PERFIL']];if(!own)tabs.push(['actions',I.actions,'AÇÕES']);root.innerHTML=`<section class="p119-hero" style="--cover:url('${esc(cover)}')"><div class="p119-avatar">${avatar(p)}<i class="is-${esc(st)}"></i></div><div class="p119-identity"><div class="p119-title"><h1>${esc(text(p.display_name||p.game_nickname||'Membro Lambreta'))}</h1></div><div class="p119-presence is-${esc(st)}"><i></i>${esc(presenceLabel(st))}</div><div class="p119-roles">${roles(p)}</div><p class="p119-bio">${esc(bio)}</p></div><img class="p119-crest" src="img/brasao-96.webp" alt=""></section><section class="p119-card"><nav class="p119-tabs ${own?'is-own':'is-public'}">${tabs.map((t,i)=>`<button type="button" data-tab="${t[0]}" class="${i===0?'is-active':''}">${t[1]}<strong>${t[2]}</strong></button>`).join('')}</nav><div class="p119-panels"><section data-panel="games"><h2>${I.game} JOGOS MAIS JOGADOS</h2><div class="p119-games">${games(p,catalog)}</div></section><section data-panel="social" hidden><h2>${I.network} REDES SOCIAIS</h2>${socialSection(p)}</section><section data-panel="profile" hidden><h2>${I.profile} INFORMAÇÕES</h2>${info(p,stats,own)}</section>${own?'':`<section data-panel="actions" hidden><h2>${I.actions} AÇÕES</h2>${actions(rel,userId)}</section>`}</div></section>`;bindTabs();bindGameImages();if(!own)await bindActions(service,rel,userId)}
render().catch(e=>{console.error('[Profile V119]',e);root.innerHTML=`<section class="p119-state"><h1>Perfil indisponível</h1><p>${esc(e?.message||'Não foi possível carregar o perfil.')}</p></section>`});
})();