-- =====================================================================
-- TEAM LAMBRETA V93.4.7 — REGRAS OBRIGATÓRIAS + AVISOS ADMINISTRATIVOS
-- Executar UMA VEZ no Supabase > SQL Editor, DEPOIS do SQL V93.4.6.
-- =====================================================================

-- Versão atual dos termos do chat usada pelo site: 2026-08-07-v1

create table if not exists public.chat_terms_acceptance (
  user_id uuid not null references auth.users(id) on delete cascade,
  terms_version text not null,
  accepted_at timestamptz not null default now(),
  primary key (user_id, terms_version)
);

create index if not exists chat_terms_acceptance_user_idx
  on public.chat_terms_acceptance(user_id, accepted_at desc);

create table if not exists public.admin_user_notices (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  report_id bigint references public.chat_reports(id) on delete set null,
  message_id bigint,
  message_text text,
  action_type text not null check (action_type in ('warning','mute','ban','message_removed')),
  duration_minutes integer,
  reason text not null,
  admin_note text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  acknowledged_at timestamptz
);

create index if not exists admin_user_notices_user_unread_idx
  on public.admin_user_notices(user_id, acknowledged_at, created_at desc);

alter table public.chat_terms_acceptance enable row level security;
alter table public.admin_user_notices enable row level security;

-- Somente RPCs SECURITY DEFINER abaixo acessam estas tabelas.
revoke all on public.chat_terms_acceptance from anon, authenticated;
revoke all on public.admin_user_notices from anon, authenticated;

-- ---------------------------------------------------------------------
-- TERMOS DO CHAT
-- ---------------------------------------------------------------------
create or replace function public.get_my_chat_terms_status(required_version text)
returns boolean
language sql
security definer
set search_path = public, auth
stable
as $$
  select auth.uid() is not null and exists (
    select 1
    from public.chat_terms_acceptance a
    where a.user_id = auth.uid()
      and a.terms_version = required_version
  );
$$;

create or replace function public.accept_chat_terms(accepted_version text)
returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if auth.uid() is null then
    raise exception 'É necessário iniciar sessão.';
  end if;

  if trim(coalesce(accepted_version,'')) <> '2026-08-07-v1' then
    raise exception 'Versão dos termos inválida ou desatualizada.';
  end if;

  insert into public.chat_terms_acceptance(user_id, terms_version, accepted_at)
  values(auth.uid(), accepted_version, now())
  on conflict (user_id, terms_version)
  do update set accepted_at = excluded.accepted_at;

  return true;
end;
$$;

-- Proteção no próprio banco: sem aceitar a versão atual, não envia chat.
create or replace function public.tl_require_current_chat_terms()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if auth.uid() is null then
    raise exception 'É necessário iniciar sessão.';
  end if;

  if new.user_id <> auth.uid() then
    raise exception 'Utilizador inválido para a mensagem.';
  end if;

  if not exists (
    select 1
    from public.chat_terms_acceptance a
    where a.user_id = auth.uid()
      and a.terms_version = '2026-08-07-v1'
  ) then
    raise exception 'Antes de usar o chat, lê e aceita as Regras da Comunidade.';
  end if;

  return new;
end;
$$;

drop trigger if exists aa_tl_require_current_chat_terms on public.chat_messages;
create trigger aa_tl_require_current_chat_terms
before insert on public.chat_messages
for each row execute function public.tl_require_current_chat_terms();

-- ---------------------------------------------------------------------
-- AVISOS ADMINISTRATIVOS DO UTILIZADOR
-- ---------------------------------------------------------------------
create or replace function public.get_my_admin_notices()
returns table(
  notice_id bigint,
  action_type text,
  duration_minutes integer,
  reason text,
  admin_note text,
  message_text text,
  created_at timestamptz
)
language sql
security definer
set search_path = public, auth
stable
as $$
  select
    n.id,
    n.action_type,
    n.duration_minutes,
    n.reason,
    n.admin_note,
    n.message_text,
    n.created_at
  from public.admin_user_notices n
  where n.user_id = auth.uid()
    and n.acknowledged_at is null
  order by n.created_at asc
  limit 20;
$$;

create or replace function public.acknowledge_admin_notice(target_notice_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  update public.admin_user_notices
  set acknowledged_at = now()
  where id = target_notice_id
    and user_id = auth.uid()
    and acknowledged_at is null;

  return found;
end;
$$;

-- ---------------------------------------------------------------------
-- AÇÃO DA ADMINISTRAÇÃO SOBRE UMA DENÚNCIA
-- Cria o aviso obrigatório automaticamente.
-- ---------------------------------------------------------------------
create or replace function public.admin_apply_chat_report_action(
  target_report_id bigint,
  moderation_action text
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  actor uuid := auth.uid();
  actor_role public.user_role;
  target_role public.user_role;
  r public.chat_reports%rowtype;
  snapshot_message text;
  target_nickname text;
  action_reason text;
  clean_action text := lower(trim(coalesce(moderation_action,'')));
begin
  if actor is null then
    raise exception 'É necessário iniciar sessão.';
  end if;

  select role into actor_role from public.profiles where id = actor;
  if actor_role not in ('master','admin','moderator') then
    raise exception 'Sem permissão para aplicar esta medida.';
  end if;

  select * into r from public.chat_reports where id = target_report_id;
  if r.id is null then
    raise exception 'Denúncia não encontrada.';
  end if;

  select role, coalesce(game_nickname, full_name, 'Utilizador')
    into target_role, target_nickname
  from public.profiles
  where id = r.reported_user_id;

  -- Mantém a hierarquia já usada pelo projeto: ninguém modera nível igual/superior.
  if r.reported_user_id <> actor
     and public.role_rank(target_role) >= public.role_rank(actor_role) then
    raise exception 'Não podes moderar alguém do mesmo nível ou superior.';
  end if;

  select message into snapshot_message
  from public.chat_messages
  where id = r.message_id;

  snapshot_message := coalesce(snapshot_message, '[mensagem indisponível]');
  action_reason := coalesce(nullif(trim(r.reason),''), 'Violação das regras de utilização do chat');

  if clean_action = 'mute_15' then
    update public.profiles
    set muted_until = now() + interval '15 minutes', updated_at = now()
    where id = r.reported_user_id;

    insert into public.admin_user_notices(
      user_id, report_id, message_id, message_text, action_type,
      duration_minutes, reason, admin_note, created_by
    ) values (
      r.reported_user_id, r.id, r.message_id, snapshot_message, 'mute',
      15, action_reason, r.details, actor
    );

    update public.chat_reports
    set status='resolved', resolved_at=now(), resolved_by=actor
    where id=r.id;

  elsif clean_action = 'ban' then
    update public.profiles
    set is_banned = true, muted_until = 'infinity'::timestamptz, updated_at = now()
    where id = r.reported_user_id;

    insert into public.admin_user_notices(
      user_id, report_id, message_id, message_text, action_type,
      reason, admin_note, created_by
    ) values (
      r.reported_user_id, r.id, r.message_id, snapshot_message, 'ban',
      action_reason, r.details, actor
    );

    update public.chat_reports
    set status='resolved', resolved_at=now(), resolved_by=actor
    where id=r.id;

  elsif clean_action = 'delete' then
    update public.chat_messages
    set is_deleted = true
    where id = r.message_id;

    insert into public.admin_user_notices(
      user_id, report_id, message_id, message_text, action_type,
      reason, admin_note, created_by
    ) values (
      r.reported_user_id, r.id, r.message_id, snapshot_message, 'message_removed',
      action_reason, r.details, actor
    );

    update public.chat_reports
    set status='resolved', resolved_at=now(), resolved_by=actor
    where id=r.id;

  elsif clean_action = 'warn' then
    insert into public.admin_user_notices(
      user_id, report_id, message_id, message_text, action_type,
      reason, admin_note, created_by
    ) values (
      r.reported_user_id, r.id, r.message_id, snapshot_message, 'warning',
      action_reason, r.details, actor
    );

    update public.chat_reports
    set status='resolved', resolved_at=now(), resolved_by=actor
    where id=r.id;

  elsif clean_action = 'dismiss' then
    update public.chat_reports
    set status='dismissed', resolved_at=now(), resolved_by=actor
    where id=r.id;

  else
    raise exception 'Ação de moderação inválida.';
  end if;

  return jsonb_build_object(
    'ok', true,
    'action', clean_action,
    'target_user_id', r.reported_user_id,
    'target_nickname', target_nickname
  );
end;
$$;

revoke all on function public.get_my_chat_terms_status(text) from public;
revoke all on function public.accept_chat_terms(text) from public;
revoke all on function public.get_my_admin_notices() from public;
revoke all on function public.acknowledge_admin_notice(bigint) from public;
revoke all on function public.admin_apply_chat_report_action(bigint,text) from public;

grant execute on function public.get_my_chat_terms_status(text) to authenticated;
grant execute on function public.accept_chat_terms(text) to authenticated;
grant execute on function public.get_my_admin_notices() to authenticated;
grant execute on function public.acknowledge_admin_notice(bigint) to authenticated;
grant execute on function public.admin_apply_chat_report_action(bigint,text) to authenticated;
