-- ============================================================
-- TEAM LAMBRETA V93.4.6 — DENÚNCIAS + BLOQUEIO PESSOAL DO CHAT
-- Executar UMA VEZ no Supabase > SQL Editor.
-- ============================================================

create table if not exists public.chat_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  reported_user_id uuid not null references auth.users(id) on delete cascade,
  message_id bigint not null references public.chat_messages(id) on delete cascade,
  reason text not null,
  details text,
  status text not null default 'pending' check (status in ('pending','resolved','dismissed')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid references auth.users(id) on delete set null
);

create index if not exists chat_reports_status_created_idx
  on public.chat_reports(status, created_at desc);

create table if not exists public.user_blocks (
  blocker_id uuid not null references auth.users(id) on delete cascade,
  blocked_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  constraint user_blocks_not_self check (blocker_id <> blocked_id)
);

alter table public.chat_reports enable row level security;
alter table public.user_blocks enable row level security;

-- O acesso é feito por RPCs SECURITY DEFINER abaixo.
revoke all on public.chat_reports from anon, authenticated;
revoke all on public.user_blocks from anon, authenticated;

create or replace function public.tl_current_role()
returns text
language sql
security definer
set search_path = public, auth
stable
as $$
  select coalesce((select role::text from public.profiles where id = auth.uid()), 'member');
$$;

create or replace function public.report_and_block_chat_message(
  target_message_id bigint,
  report_reason text,
  report_details text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  actor uuid := auth.uid();
  target uuid;
  clean_reason text := left(trim(coalesce(report_reason,'')), 80);
  clean_details text := nullif(left(trim(coalesce(report_details,'')), 500), '');
  new_report_id bigint;
begin
  if actor is null then
    raise exception 'É necessário iniciar sessão.';
  end if;

  if clean_reason = '' then
    raise exception 'Escolhe um motivo para a denúncia.';
  end if;

  select user_id into target
  from public.chat_messages
  where id = target_message_id and coalesce(is_deleted,false) = false;

  if target is null then
    raise exception 'Mensagem não encontrada.';
  end if;

  if target = actor then
    raise exception 'Não podes denunciar a tua própria mensagem.';
  end if;

  insert into public.chat_reports(reporter_id, reported_user_id, message_id, reason, details)
  values(actor, target, target_message_id, clean_reason, clean_details)
  returning id into new_report_id;

  insert into public.user_blocks(blocker_id, blocked_id)
  values(actor, target)
  on conflict (blocker_id, blocked_id) do nothing;

  return jsonb_build_object('ok', true, 'report_id', new_report_id, 'blocked_user_id', target);
end;
$$;

create or replace function public.block_chat_user(target_user_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
declare actor uuid := auth.uid();
begin
  if actor is null then raise exception 'É necessário iniciar sessão.'; end if;
  if target_user_id is null or target_user_id = actor then return false; end if;
  insert into public.user_blocks(blocker_id, blocked_id)
  values(actor, target_user_id)
  on conflict (blocker_id, blocked_id) do nothing;
  return true;
end;
$$;

create or replace function public.unblock_chat_user(target_user_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  delete from public.user_blocks
  where blocker_id = auth.uid() and blocked_id = target_user_id;
  return found;
end;
$$;

create or replace function public.get_my_blocked_chat_users()
returns table(blocked_id uuid)
language sql
security definer
set search_path = public, auth
stable
as $$
  select ub.blocked_id
  from public.user_blocks ub
  where ub.blocker_id = auth.uid();
$$;

create or replace function public.admin_list_chat_reports()
returns table(
  report_id bigint,
  message_id bigint,
  message_text text,
  reason text,
  details text,
  status text,
  created_at timestamptz,
  reporter_id uuid,
  reporter_nickname text,
  reported_user_id uuid,
  reported_nickname text
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if public.tl_current_role() not in ('master','admin','moderator','staff') then
    raise exception 'Sem permissão para ver denúncias.';
  end if;

  return query
  select
    r.id,
    r.message_id,
    m.message,
    r.reason,
    r.details,
    r.status,
    r.created_at,
    r.reporter_id,
    coalesce(pr.game_nickname, pr.full_name, 'Utilizador')::text,
    r.reported_user_id,
    coalesce(pt.game_nickname, pt.full_name, 'Utilizador')::text
  from public.chat_reports r
  join public.chat_messages m on m.id = r.message_id
  left join public.profiles pr on pr.id = r.reporter_id
  left join public.profiles pt on pt.id = r.reported_user_id
  order by (r.status = 'pending') desc, r.created_at desc
  limit 200;
end;
$$;

create or replace function public.admin_resolve_chat_report(
  target_report_id bigint,
  new_status text default 'resolved'
)
returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if public.tl_current_role() not in ('master','admin','moderator','staff') then
    raise exception 'Sem permissão.';
  end if;

  if new_status not in ('resolved','dismissed','pending') then
    raise exception 'Estado inválido.';
  end if;

  update public.chat_reports
  set status = new_status,
      resolved_at = case when new_status = 'pending' then null else now() end,
      resolved_by = case when new_status = 'pending' then null else auth.uid() end
  where id = target_report_id;
  return found;
end;
$$;

revoke all on function public.report_and_block_chat_message(bigint,text,text) from public;
revoke all on function public.block_chat_user(uuid) from public;
revoke all on function public.unblock_chat_user(uuid) from public;
revoke all on function public.get_my_blocked_chat_users() from public;
revoke all on function public.admin_list_chat_reports() from public;
revoke all on function public.admin_resolve_chat_report(bigint,text) from public;

grant execute on function public.report_and_block_chat_message(bigint,text,text) to authenticated;
grant execute on function public.block_chat_user(uuid) to authenticated;
grant execute on function public.unblock_chat_user(uuid) to authenticated;
grant execute on function public.get_my_blocked_chat_users() to authenticated;
grant execute on function public.admin_list_chat_reports() to authenticated;
grant execute on function public.admin_resolve_chat_report(bigint,text) to authenticated;
