-- Team Lambreta V93.8.1 — RESET SEGURO DO PROGRESSO BETA
-- Faz snapshot antes de zerar. NÃO apaga perfis, mensagens, tópicos ou conteúdo.
-- Rode UMA VEZ quando quiser iniciar uma nova temporada/beta do zero.

begin;

-- Histórico de snapshots dos contadores por utilizador.
create table if not exists public.community_progress_beta_backups (
  id bigint generated by default as identity primary key,
  reset_batch text not null,
  snapshot_at timestamptz not null default now(),
  user_id uuid not null,
  profile_snapshot jsonb not null default '{}'::jsonb,
  progress_snapshot jsonb not null default '{}'::jsonb
);

create index if not exists community_progress_beta_backups_batch
  on public.community_progress_beta_backups(reset_batch, snapshot_at desc);
create index if not exists community_progress_beta_backups_user
  on public.community_progress_beta_backups(user_id, snapshot_at desc);

-- Histórico dos eventos que geraram XP/progresso antes do reset.
create table if not exists public.community_progress_events_beta_backups (
  id bigint generated by default as identity primary key,
  reset_batch text not null,
  snapshot_at timestamptz not null default now(),
  source_event_id bigint,
  user_id uuid,
  event_snapshot jsonb not null default '{}'::jsonb
);

create index if not exists community_progress_events_beta_backups_batch
  on public.community_progress_events_beta_backups(reset_batch, snapshot_at desc);

-- Um mesmo identificador para todo este reset.
create temporary table tl_beta_reset_batch(batch text) on commit drop;
insert into tl_beta_reset_batch(batch)
values ('beta_reset_' || to_char(clock_timestamp(), 'YYYYMMDD_HH24MISS_MS'));

-- 1) BACKUP dos números atuais (mesmo quem ainda não tiver linha em community_progress).
insert into public.community_progress_beta_backups(
  reset_batch, user_id, profile_snapshot, progress_snapshot
)
select
  b.batch,
  p.id,
  jsonb_build_object(
    'xp', coalesce(p.xp,0),
    'level', coalesce(p.level,1),
    'active_seconds', coalesce(p.active_seconds,0),
    'afk_seconds', coalesce(p.afk_seconds,0),
    'live_seconds', coalesce(p.live_seconds,0),
    'forum_topics_count', coalesce(p.forum_topics_count,0),
    'forum_replies_count', coalesce(p.forum_replies_count,0),
    'forum_thanks_count', coalesce(p.forum_thanks_count,0),
    'event_participations', coalesce(p.event_participations,0),
    'achievements_count', coalesce(p.achievements_count,0)
  ),
  case when cp.user_id is null then '{}'::jsonb else to_jsonb(cp) end
from public.profiles p
cross join tl_beta_reset_batch b
left join public.community_progress cp on cp.user_id=p.id;

-- 2) BACKUP do log de ações/XP desta fase beta.
insert into public.community_progress_events_beta_backups(
  reset_batch, source_event_id, user_id, event_snapshot
)
select b.batch, e.id, e.user_id, to_jsonb(e)
from public.community_progress_events e
cross join tl_beta_reset_batch b;

-- 3) ZERA o estado agregado do progresso.
update public.community_progress
set
  xp = 0,
  level = 1,
  active_seconds = 0,
  afk_seconds = 0,
  live_seconds = 0,
  forum_topics = 0,
  forum_replies = 0,
  forum_thanks = 0,
  event_participations = 0,
  achievements_count = 0,
  last_active_at = null,
  updated_at = now();

-- Garante linha zerada também para perfis que ainda não entraram no sistema novo.
insert into public.community_progress(
  user_id, xp, level, active_seconds, afk_seconds, live_seconds,
  forum_topics, forum_replies, forum_thanks, event_participations,
  achievements_count, last_active_at, updated_at
)
select
  p.id, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, null, now()
from public.profiles p
on conflict(user_id) do nothing;

-- 4) SINCRONIZA os contadores espelhados em profiles.
update public.profiles
set
  xp = 0,
  level = 1,
  active_seconds = 0,
  afk_seconds = 0,
  live_seconds = 0,
  forum_topics_count = 0,
  forum_replies_count = 0,
  forum_thanks_count = 0,
  event_participations = 0,
  achievements_count = 0;

-- 5) Limpa o log operacional antigo APÓS o backup.
-- Isso também libera as dedupe_keys para o novo beta contar ações do zero.
delete from public.community_progress_events;

commit;

-- Conferência rápida: deve mostrar tudo zerado e level=1.
select
  count(*) as usuarios,
  coalesce(sum(xp),0) as xp_total,
  coalesce(sum(active_seconds),0) as segundos_ativos,
  coalesce(sum(live_seconds),0) as segundos_live,
  coalesce(sum(event_participations),0) as eventos,
  min(level) as nivel_minimo,
  max(level) as nivel_maximo
from public.community_progress;

-- Último backup criado (para confirmar que o snapshot existe).
select reset_batch, snapshot_at, count(*) as perfis_salvos
from public.community_progress_beta_backups
group by reset_batch, snapshot_at
order by snapshot_at desc
limit 1;
