-- Team Lambreta V93.8.0 — progresso real, anti-AFK, fórum, eventos, lives, XP e Hall

alter table public.profiles
  add column if not exists xp bigint not null default 0,
  add column if not exists forum_replies_count integer not null default 0,
  add column if not exists forum_thanks_count integer not null default 0,
  add column if not exists event_participations integer not null default 0,
  add column if not exists achievements_count integer not null default 0;

create table if not exists public.community_progress (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  xp bigint not null default 0,
  level integer not null default 1,
  active_seconds bigint not null default 0,
  afk_seconds bigint not null default 0,
  live_seconds bigint not null default 0,
  forum_topics integer not null default 0,
  forum_replies integer not null default 0,
  forum_thanks integer not null default 0,
  event_participations integer not null default 0,
  achievements_count integer not null default 0,
  last_active_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.community_progress_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null,
  amount integer not null default 1,
  xp_awarded integer not null default 0,
  dedupe_key text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists community_progress_event_dedupe
  on public.community_progress_events(user_id,event_type,dedupe_key)
  where dedupe_key is not null;
create index if not exists community_progress_events_user_time
  on public.community_progress_events(user_id,created_at desc);
create index if not exists community_progress_ranking
  on public.community_progress(xp desc,active_seconds desc);

alter table public.community_progress enable row level security;
alter table public.community_progress_events enable row level security;

drop policy if exists "progress authenticated read" on public.community_progress;
create policy "progress authenticated read" on public.community_progress for select to authenticated using (true);

drop policy if exists "progress events own read" on public.community_progress_events;
create policy "progress events own read" on public.community_progress_events for select to authenticated
using (user_id=auth.uid() or exists (select 1 from public.profiles p where p.id=auth.uid() and p.role::text in ('master','admin','staff','moderator','dev')));

grant select on public.community_progress to authenticated;
grant select on public.community_progress_events to authenticated;
grant usage,select on all sequences in schema public to authenticated;

create or replace function public.tl_progress_level(p_xp bigint)
returns integer language sql immutable as $$
  select greatest(1, least(100, 1 + floor(greatest(p_xp,0)::numeric / 250)::integer));
$$;

create or replace function public.tl_record_progress(
  p_event_type text,
  p_amount integer default 1,
  p_dedupe_key text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns public.community_progress
language plpgsql
security definer
set search_path=public
as $$
declare
  v_uid uuid := auth.uid();
  v_amount integer := greatest(coalesce(p_amount,1),0);
  v_xp integer := 0;
  v_inserted boolean := true;
  v_progress public.community_progress;
  v_before_active bigint := 0;
  v_before_live bigint := 0;
begin
  if v_uid is null then raise exception 'Login necessário'; end if;

  insert into public.community_progress(user_id) values(v_uid)
  on conflict(user_id) do nothing;
  select active_seconds,live_seconds into v_before_active,v_before_live
  from public.community_progress where user_id=v_uid;

  -- Limites server-side: o browser nunca pode mandar horas de uma vez.
  if p_event_type in ('active_seconds','afk_seconds','live_seconds') then
    v_amount := least(v_amount, 120);
  else
    v_amount := least(v_amount, 1);
  end if;

  -- XP: presença real 1 XP/2min; live ativa 1 XP/min; fórum e evento por ação única.
  v_xp := case p_event_type
    when 'active_seconds' then (floor((v_before_active + v_amount) / 120.0) - floor(v_before_active / 120.0))::int
    when 'live_seconds' then (floor((v_before_live + v_amount) / 60.0) - floor(v_before_live / 60.0))::int
    when 'forum_topic' then 20
    when 'forum_reply' then 8
    when 'forum_thank' then 5
    when 'event_participation' then 50
    else 0
  end;

  begin
    insert into public.community_progress_events(user_id,event_type,amount,xp_awarded,dedupe_key,metadata)
    values(v_uid,p_event_type,v_amount,v_xp,nullif(p_dedupe_key,''),coalesce(p_metadata,'{}'::jsonb));
  exception when unique_violation then
    v_inserted := false;
  end;

  if not v_inserted then
    select * into v_progress from public.community_progress where user_id=v_uid;
    return v_progress;
  end if;

  update public.community_progress set
    xp = xp + v_xp,
    active_seconds = active_seconds + case when p_event_type='active_seconds' then v_amount else 0 end,
    afk_seconds = afk_seconds + case when p_event_type='afk_seconds' then v_amount else 0 end,
    live_seconds = live_seconds + case when p_event_type='live_seconds' then v_amount else 0 end,
    forum_topics = forum_topics + case when p_event_type='forum_topic' then 1 else 0 end,
    forum_replies = forum_replies + case when p_event_type='forum_reply' then 1 else 0 end,
    forum_thanks = forum_thanks + case when p_event_type='forum_thank' then 1 else 0 end,
    event_participations = event_participations + case when p_event_type='event_participation' then 1 else 0 end,
    last_active_at = case when p_event_type in ('active_seconds','live_seconds') then now() else last_active_at end,
    updated_at = now()
  where user_id=v_uid
  returning * into v_progress;

  update public.community_progress
  set level=public.tl_progress_level(xp)
  where user_id=v_uid
  returning * into v_progress;

  update public.profiles set
    xp=v_progress.xp,
    level=v_progress.level,
    active_seconds=v_progress.active_seconds,
    afk_seconds=v_progress.afk_seconds,
    live_seconds=v_progress.live_seconds,
    forum_topics_count=v_progress.forum_topics,
    forum_replies_count=v_progress.forum_replies,
    forum_thanks_count=v_progress.forum_thanks,
    event_participations=v_progress.event_participations,
    achievements_count=v_progress.achievements_count
  where id=v_uid;

  return v_progress;
end;
$$;

grant execute on function public.tl_record_progress(text,integer,text,jsonb) to authenticated;

-- Agradecimento/like recebido: recompensa o autor, nunca o próprio utilizador, uma vez por tópico + pessoa.
create or replace function public.tl_give_forum_thank(p_target uuid,p_topic_key text)
returns boolean
language plpgsql
security definer
set search_path=public
as $$
declare
  v_actor uuid := auth.uid();
  v_key text;
begin
  if v_actor is null or p_target is null or p_target=v_actor then return false; end if;
  v_key := v_actor::text || ':' || coalesce(p_topic_key,'topic');
  begin
    insert into public.community_progress(user_id) values(p_target) on conflict(user_id) do nothing;
    insert into public.community_progress_events(user_id,event_type,amount,xp_awarded,dedupe_key,metadata)
    values(p_target,'forum_thank',1,5,v_key,jsonb_build_object('from',v_actor,'topic',p_topic_key));
  exception when unique_violation then return false; end;

  update public.community_progress
  set forum_thanks=forum_thanks+1,xp=xp+5,updated_at=now()
  where user_id=p_target;
  update public.community_progress set level=public.tl_progress_level(xp) where user_id=p_target;
  update public.profiles p set
    xp=cp.xp,level=cp.level,forum_thanks_count=cp.forum_thanks
  from public.community_progress cp where p.id=p_target and cp.user_id=p_target;
  return true;
end;
$$;
grant execute on function public.tl_give_forum_thank(uuid,text) to authenticated;

-- Migra os contadores já existentes quando houver.
insert into public.community_progress(user_id,level,active_seconds,afk_seconds,live_seconds,forum_topics)
select id,greatest(coalesce(level,1),1),coalesce(active_seconds,0),coalesce(afk_seconds,0),coalesce(live_seconds,0),coalesce(forum_topics_count,0)
from public.profiles
on conflict(user_id) do update set
  level=greatest(public.community_progress.level,excluded.level),
  active_seconds=greatest(public.community_progress.active_seconds,excluded.active_seconds),
  afk_seconds=greatest(public.community_progress.afk_seconds,excluded.afk_seconds),
  live_seconds=greatest(public.community_progress.live_seconds,excluded.live_seconds),
  forum_topics=greatest(public.community_progress.forum_topics,excluded.forum_topics);
