(()=>{
  'use strict';
  const KEY='tl_update_tour_v1';
  const SUPABASE_URL='https://ahiatqnokyhfpailobjx.supabase.co',SUPABASE_KEY='sb_publishable_qgwMhZPrB_3cFv3yCMcToA_9nDvHz-O';
  const steps=[
    {target:'forum-structure',url:'forum.html',kind:'NOVO',title:'Fórum renovado',body:'Categorias, pastas, tópicos e respostas agora ficam organizados como uma comunidade real.'},
    {target:'forum-profile',url:'forum.html',kind:'NOVO',title:'Perfil do Fórum',body:'Abra o seu perfil para configurar nickname, avatar e informações públicas.'},
    {target:'forum-share',url:'forum.html',kind:'MELHORIA',title:'Compartilhar publicação',body:'Use o compartilhamento para copiar ou enviar o deep link exato de um tópico ou resposta.'},
    {target:'topic-moderation',url:'forum.html',kind:'MELHORIA',title:'Moderação de tópicos',body:'Moderadores podem fixar, trancar e fechar tópicos sem apagar o conteúdo.'},
    {target:'buddy-list',url:'buddy.html',kind:'NOVO',title:'Buddy System',body:'Encontre Buddies, acompanhe presença e abra conversas privadas somente por texto.'},
    {target:'updates-page',url:'atualizacoes.html',kind:'COMUNIDADE',title:'Atualizações',body:'Consulte o histórico de novidades e reveja este tour quando quiser.'}
  ];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const page=()=>location.pathname.split('/').pop()||'home.html';
  function targetEl(id){
    const selectors={
      'forum-structure':['[data-tour="forum-structure"]','#forumBoardView','#forumApplication'],
      'forum-profile':['[data-tour="forum-profile"]','#forumMyProfileButton'],
      'forum-share':['[data-tour="forum-share"]','[data-share-topic]'],
      'topic-moderation':['[data-tour="topic-moderation"]','[data-topic-moderation-toggle]'],
      'buddy-list':['[data-tour="buddy-list"]','#buddyApp','.buddy-sidebar'],
      'team-roster':['[data-tour="team-roster"]','#teamRosterGrid','.team-esports-grid'],
      'updates-page':['[data-tour="updates-page"]','.updates-page']
    };
    return (selectors[id]||[`[data-tour="${CSS.escape(id)}"]`]).map(s=>document.querySelector(s)).find(Boolean);
  }
  function validUrl(value){if(typeof value!=='string')return false;const raw=value.trim();if(!raw||raw==='undefined'||raw==='null')return false;try{const url=new URL(raw,location.href);return ['http:','https:'].includes(url.protocol)&&url.origin===location.origin&&/\.html$/i.test(url.pathname)}catch{return false}}
  function validTarget(value){return typeof value==='string'&&value.trim()&&value!=='undefined'&&value!=='null'}
  function close(){const root=document.querySelector('.tl-tour-root');if(root?._reposition)window.removeEventListener('resize',root._reposition);root?.remove();document.querySelectorAll('.tl-tour-target').forEach(el=>{el.classList.remove('tl-tour-target');el.style.removeProperty('z-index')});window.dispatchEvent(new CustomEvent('tl-tour-closed'));}
  function fallback(message='Esta novidade ainda não tem uma demonstração disponível.'){
    close();const root=document.createElement('div');root.className='tl-tour-root';root.innerHTML=`<div class="tl-tour-overlay is-open" aria-hidden="true"></div><aside class="tl-tour-card tl-tour-fallback" role="status"><small>ATUALIZAÇÕES</small><h2>Me mostra</h2><p>${esc(message)}</p><div class="tl-tour-actions"><button type="button" data-tour-close>Fechar</button></div></aside>`;document.body.appendChild(root);root.querySelector('[data-tour-close]').onclick=close;root.querySelector('.tl-tour-overlay').onclick=close;}
  function save(state){sessionStorage.setItem(KEY,JSON.stringify(state));}
  function current(){try{return JSON.parse(sessionStorage.getItem(KEY)||'null')}catch{return null}}
  async function findForumTopic(){try{const response=await fetch(`${SUPABASE_URL}/rest/v1/forum_topics?select=id,title,is_pinned,status&status=eq.approved&order=is_pinned.desc,last_activity_at.desc&limit=20`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`}});const rows=response.ok?await response.json():[];const welcome=rows.find(row=>/bem[- ]vindos/i.test(String(row.title||'')));return String((welcome||rows[0]||{}).id||'')||null}catch{return null}}
  async function resolveStep(step,state={}){if(!step)return null;if(!['forum-share','topic-moderation'].includes(step.target))return {...step};const topicId=state.topicId||await findForumTopic();return topicId?{...step,url:`forum.html?topic=${encodeURIComponent(topicId)}`,topicId}:null}
  function placeCard(card,el){if(innerWidth<=650){card.style.top='';card.style.left='';return}const margin=18,gap=14,rect=el.getBoundingClientRect();card.style.maxHeight=`calc(100vh - ${margin*2}px)`;card.style.overflowY='auto';const width=Math.min(360,innerWidth-margin*2),height=Math.min(card.offsetHeight,innerHeight-margin*2);let top=rect.bottom+gap,left=rect.left;if(top+height>innerHeight-margin)top=rect.top-height-gap;if(top<margin){top=Math.max(margin,Math.min(innerHeight-height-margin,rect.top));left=rect.right+gap;if(left+width>innerWidth-margin)left=rect.left-width-gap}if(left+width>innerWidth-margin)left=innerWidth-width-margin;if(left<margin)left=margin;if(top+height>innerHeight-margin)top=innerHeight-height-margin;card.style.top=`${Math.round(top)}px`;card.style.left=`${Math.round(left)}px`}
  async function go(state,index){const step=await resolveStep(steps[index],state);if(!step||!validUrl(step.url)||!validTarget(step.target)){fallback('Esta etapa do tour não possui um destino válido. Você pode continuar usando o site normalmente.');return}const nextState={...state,index,topicId:step.topicId||state.topicId};save(nextState);const targetUrl=new URL(step.url,location.href);if(page()!==targetUrl.pathname.split('/').pop()||(['forum-share','topic-moderation'].includes(step.target)&&new URLSearchParams(location.search).get('topic')!==step.topicId)){targetUrl.searchParams.set('tlTour','1');location.href=targetUrl.href;return}setTimeout(()=>open(nextState,index,step),80)}
  function open(state,index,customStep=null){const step=customStep||steps[index];const individual=Boolean(customStep);if(!step||!validTarget(step.target)||!validUrl(step.url)){fallback('Esta novidade ainda não tem uma página demonstrável configurada.');return}const el=targetEl(step.target);if(!el){if(!individual&&index<steps.length-1)return go(state,index+1);fallback('O recurso ainda não está disponível nesta página.');return}document.querySelector('.tl-tour-root')?.remove();el.classList.add('tl-tour-target');el.scrollIntoView({behavior:'smooth',block:'center',inline:'nearest'});const root=document.createElement('div');root.className='tl-tour-root';root.innerHTML=`<div class="tl-tour-overlay is-open" aria-hidden="true"></div><aside class="tl-tour-card" role="dialog" aria-label="Tour da atualização"><small>${esc(step.kind||'NOVIDADE')}${individual?'':' · '+(index+1)+' de '+steps.length}</small><h2>${esc(step.title)}</h2><p>${esc(step.body)}</p><div class="tl-tour-actions"><button type="button" data-tour-skip>${individual?'Fechar':'Pular tour'}</button>${!individual&&index?'<button type="button" data-tour-prev>Voltar</button>':''}<button type="button" data-tour-next>${individual||index===steps.length-1?'Concluir':'Próximo →'}</button></div></aside>`;document.body.appendChild(root);const card=root.querySelector('.tl-tour-card');const reposition=()=>placeCard(card,el);root._reposition=reposition;requestAnimationFrame(()=>requestAnimationFrame(reposition));setTimeout(reposition,350);window.addEventListener('resize',reposition,{passive:true});root.querySelector('[data-tour-skip]').onclick=()=>{if(!individual)localStorage.setItem('tl_update_tour_seen','1');sessionStorage.removeItem(KEY);close()};root.querySelector('[data-tour-prev]')?.addEventListener('click',()=>go(state,Math.max(0,index-1)));root.querySelector('[data-tour-next]').onclick=()=>{if(individual||index===steps.length-1){if(!individual)localStorage.setItem('tl_update_tour_seen','1');sessionStorage.removeItem(KEY);close()}else go(state,index+1)};root.querySelector('.tl-tour-overlay').onclick=close;}
  function startFull(){save({release:'2026.08.15',index:0});go({release:'2026.08.15'},0)}
  async function startItem(meta){if(!meta||!validUrl(meta.tour_url||meta.url)||!validTarget(meta.tour_target||meta.target)){fallback('Esta novidade ainda não possui uma demonstração disponível.');return}let normalized={...meta,url:meta.tour_url||meta.url,target:meta.tour_target||meta.target};if(['forum-share','topic-moderation'].includes(normalized.target)){const topicId=await findForumTopic();if(!topicId){fallback('Não foi encontrado um tópico aprovado para demonstrar esta novidade.');return}normalized={...normalized,url:`forum.html?topic=${encodeURIComponent(topicId)}`,topicId}}const state={release:'2026.08.15',index:0,individual:normalized,topicId:normalized.topicId};sessionStorage.setItem(KEY,JSON.stringify(state));const targetUrl=new URL(normalized.url,location.href);if(page()!==targetUrl.pathname.split('/').pop()||normalized.topicId){targetUrl.searchParams.set('tlTour','1');location.href=targetUrl.href;return}setTimeout(()=>open({...state},0,normalized),80)}
  window.TLStartUpdateTour=startFull;window.TLStartUpdateItem=startItem;window.TLCloseTour=close;
  async function init(){const state=current();const q=new URLSearchParams(location.search);if(!state||q.get('tlTour')!=='1')return;if(state.individual){if(!validUrl(state.individual.url||state.individual.tour_url)||!validTarget(state.individual.target||state.individual.tour_target)){fallback('Esta novidade ainda não possui uma demonstração disponível.');return}const normalized={...state.individual,url:state.individual.url||state.individual.tour_url,target:state.individual.target||state.individual.tour_target};const el=targetEl(normalized.target);if(el){open({release:state.release,individual:normalized},0,normalized)}else setTimeout(init,300);return}const index=Number(state.index)||0;const step=await resolveStep(steps[index],state);if(!step||!validUrl(step.url)||!validTarget(step.target)){fallback('Esta etapa do tour não possui um destino válido.');return}if(new URL(step.url,location.href).pathname.split('/').pop()!==page()||(['forum-share','topic-moderation'].includes(step.target)&&q.get('topic')!==step.topicId)){save({...state,index,topicId:step.topicId||state.topicId});const targetUrl=new URL(step.url,location.href);targetUrl.searchParams.set('tlTour','1');location.href=targetUrl.href;return}const el=targetEl(step.target);if(!el){setTimeout(init,350);return}open({...state,topicId:step.topicId||state.topicId},index,step)}
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.querySelector('.tl-tour-root')){sessionStorage.removeItem(KEY);close()}});document.addEventListener('DOMContentLoaded',init);if(document.readyState!=='loading')init();
})();
