(()=>{'use strict';
const SUPABASE_URL='https://ahiatqnokyhfpailobjx.supabase.co',SUPABASE_KEY='sb_publishable_qgwMhZPrB_3cFv3yCMcToA_9nDvHz-O';
const sb=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY),$=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const TOUR_FALLBACK={
 'Fórum com estrutura de comunidade':{tour_url:'forum.html',tour_target:'forum-structure',tour_enabled:true},
 'Perfis e editor do Fórum':{tour_url:'forum.html',tour_target:'forum-profile',tour_enabled:true},
 'Reações, partilhas e moderação':{tour_url:'forum.html',tour_target:'forum-share',tour_enabled:true},
 'Buddy com experiência de lista de amigos':{tour_url:'buddy.html',tour_target:'buddy-list',tour_enabled:true},
 'Team mais consistente em qualquer tela':{tour_url:'team.html',tour_target:'team-roster',tour_enabled:true}
};
const FALLBACK={id:'2026.08.15',version:'2026.08.15',title:'Grande atualização da Comunidade',summary:'O Fórum, a Team, o Buddy e várias áreas do Team Lambreta receberam uma grande evolução.',content:'A comunidade ganhou uma base mais organizada para conversar, conhecer membros, acompanhar novidades e participar do Team. Esta atualização reúne as melhorias lançadas em 15 de agosto de 2026.',category:'COMUNIDADE',published_at:'2026-08-15',items:[
 {kind:'NOVO',title:'Fórum com estrutura de comunidade',body:'O Fórum agora organiza o conteúdo em categorias, pastas, tópicos e respostas. Cada tópico tem endereço próprio, breadcrumbs e links diretos para publicações, deixando a conversa muito mais fácil de acompanhar.'},
 {kind:'NOVO',title:'Perfis e editor do Fórum',body:'Cada membro pode configurar nickname, avatar, país, jogos, plataformas, modos de jogo e bio. Essas informações aparecem num mini perfil ao lado das publicações, com estatísticas reais e data original de entrada na comunidade.'},
 {kind:'NOVO',title:'Menções e editor avançado',body:'O editor permite formatação leve, emojis, citações e menções contextuais aos participantes do tópico. O autocomplete mostra avatar, cargo e jogo, e a menção publicada abre um preview seguro do perfil.'},
 {kind:'MELHORIA',title:'Reações, partilhas e moderação',body:'Posts agora têm likes, dislikes, partilha de deep links e ações de moderação mais claras. Respostas e publicações podem ser removidas sem quebrar os links, e tópicos podem ser fixados, trancados ou fechados quando essa moderação estiver disponível.'},
 {kind:'SEGURANÇA',title:'XP baseado em atividade válida',body:'O progresso considera apenas tópicos, respostas e likes válidos. Conteúdo removido, reações próprias e repetições não geram recompensas indevidas, evitando farm de XP.'},
 {kind:'VISUAL',title:'Team mais consistente em qualquer tela',body:'As imagens dos membros passaram a respeitar melhor o enquadramento 4:5, os cards usam o espaço da foto com mais consistência e o perfil da Team foi ajustado para mobile, tablet e desktop.'},
 {kind:'NOVO',title:'Buddy com experiência de lista de amigos',body:'O Buddy evoluiu para uma lista gamer de Pessoas, Buddies, Pedidos e Bloqueados, com presença online/offline, pedidos de amizade, perfil rápido e conversas privadas somente por texto.'},
 {kind:'MELHORIA',title:'Participe, Admin e página inicial',body:'A navegação da Participe foi alinhada ao menu global, o Admin ganhou uma Central de Ajuda própria, o carrossel mobile da Home foi restaurado e o fluxo de inscrições passou a ter notificações administrativas por e-mail quando o domínio estiver configurado.'}
]};
let updates=[],session=null,isAdmin=false;
function tourMeta(item){return item?.tour_enabled&&item.tour_target?item:TOUR_FALLBACK[item?.title]||null}
function runTourItem(meta){const start=()=>window.TLStartUpdateItem?window.TLStartUpdateItem(meta):setTimeout(start,120);start()}
function decorateTours(){
  document.querySelector('.updates-page')?.setAttribute('data-tour','updates-page');
  const hero=document.querySelector('.updates-hero');
  if(hero&&!hero.querySelector('[data-start-update-tour]')){const b=document.createElement('button');b.type='button';b.className='updates-tour-button';b.dataset.startUpdateTour='true';b.textContent='✨ Fazer tour da atualização';b.onclick=()=>{const start=()=>window.TLStartUpdateTour?window.TLStartUpdateTour():setTimeout(start,120);start()};hero.appendChild(b)}
  updates.forEach(update=>{const release=document.querySelector(`[data-release="${CSS.escape(String(update.id))}"]`);if(!release)return;[...(release.querySelectorAll('.updates-item'))].forEach((node,index)=>{const item=update.items?.[index],meta=tourMeta(item);if(!meta||node.querySelector('[data-show-update]'))return;const b=document.createElement('button');b.type='button';b.className='updates-show-button';b.dataset.showUpdate='true';b.textContent='✨ Me mostra';b.setAttribute('aria-label',`Me mostra: ${item.title}`);b.onclick=()=>runTourItem({...meta,title:item.title,body:item.body,kind:item.kind});node.appendChild(b)})})
}
function formatDate(value){return new Date(`${value}T12:00:00`).toLocaleDateString('pt-PT',{day:'2-digit',month:'short',year:'numeric'}).replace('.','').toUpperCase()}
function render(){const list=$('updatesList');if(!updates.length){list.innerHTML='<p class="updates-empty">Ainda não há atualizações publicadas.</p>';return}list.innerHTML=updates.map((u,i)=>`<article class="updates-release" id="release-${esc(u.id)}" data-release="${esc(u.id)}"><header class="updates-release-head" tabindex="0" role="button" aria-expanded="${i===0?'true':'false'}"><time class="updates-date">${formatDate(u.published_at)}</time><div><h2>${esc(u.title)}</h2><p>${esc(u.summary)}</p></div><b class="updates-chevron">${i===0?'−':'+'}</b></header><div class="updates-release-body" ${i===0?'':'hidden'}><p class="updates-release-intro">${esc(u.content||'')}</p><div class="updates-items">${(u.items||[]).map(item=>`<article class="updates-item"><h3><span class="updates-badge updates-badge-${esc(item.kind)}">${esc(item.kind)}</span>${esc(item.title)}</h3><p>${esc(item.body)}</p></article>`).join('')}</div></div></article>`).join('');list.querySelectorAll('.updates-release-head').forEach(head=>{const toggle=()=>{const body=head.nextElementSibling,open=body.hidden;body.hidden=!open;head.setAttribute('aria-expanded',String(open));head.querySelector('.updates-chevron').textContent=open?'−':'+';const update=updates.find(u=>String(u.id)===head.closest('[data-release]')?.dataset.release);if(open&&update)markSeen(update);decorateTours()};head.onclick=toggle;head.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}}});decorateTours();const wanted=new URLSearchParams(location.search).get('release');if(wanted){const target=updates.find(u=>String(u.id)===wanted||u.version===wanted);if(target){const el=$(`[data-release="${CSS.escape(String(target.id))}"]`);el?.scrollIntoView({behavior:'smooth',block:'start'});markSeen(target)}}}
async function load(){let rows=[],items=[];if(sb){const s=await sb.auth.getSession();session=s.data.session;const pr=await sb.from('profiles').select('role').eq('id',session?.user?.id||'').maybeSingle();isAdmin=['master','admin'].includes(String(pr.data?.role||'').toLowerCase());const r=await sb.from('site_updates').select('*').order('published_at',{ascending:false});if(!r.error)rows=r.data||[];if(rows.length){const ir=await sb.from('site_update_items').select('*').in('update_id',rows.map(x=>x.id)).order('sort_order');if(!ir.error)items=ir.data||[]}}if(!rows.length)rows=[FALLBACK];updates=rows.map(u=>({...u,items:items.filter(i=>i.update_id===u.id)}));if(updates[0]&&!updates[0].items.length&&updates[0].version===FALLBACK.version)updates[0]=FALLBACK;render();await showNotice();if(isAdmin)renderAdmin()}
 async function markSeen(update){const key=`tl_seen_update_${update.version}`;localStorage.setItem(key,'1');const link=document.querySelector('[data-updates-new]');link?.removeAttribute('data-updates-new');link?.querySelector('b[aria-label="Novidade"]')?.remove();if(session&&sb&&update.id!==FALLBACK.id)await sb.from('site_update_reads').upsert({user_id:session.user.id,update_id:update.id,seen_at:new Date().toISOString()})}
async function showNotice(){const latest=updates[0];if(!latest)return;let seen=localStorage.getItem(`tl_seen_update_${latest.version}`)==='1';if(session&&sb&&latest.id!==FALLBACK.id){const r=await sb.from('site_update_reads').select('update_id').eq('user_id',session.user.id).eq('update_id',latest.id).maybeSingle();seen=seen||Boolean(r.data)}const q=new URLSearchParams(location.search).get('release');if(!seen&&!q){$('updatesNotice').hidden=false;$('updatesNoticeText').textContent=`${latest.title} — ${latest.summary}`;$('updatesNoticeOpen').onclick=()=>{location.href=`atualizacoes.html?release=${encodeURIComponent(latest.id)}`}}}
function renderAdmin(){const box=$('updatesAdmin');box.hidden=false;const form=$('updatesForm'),status=$('updatesAdminStatus');$('updatesDate').value=new Date().toISOString().slice(0,10);$('updatesReset').onclick=()=>{form.reset();$('updatesId').value='';$('updatesDate').value=new Date().toISOString().slice(0,10)};form.onsubmit=async e=>{e.preventDefault();if(!sb||!session)return;const payload={version:$('updatesVersion').value.trim(),title:$('updatesTitle').value.trim(),summary:$('updatesSummary').value.trim(),content:$('updatesContent').value.trim(),category:$('updatesCategory').value,published_at:$('updatesDate').value,is_published:$('updatesPublished').value==='true',created_by:session.user.id,updated_at:new Date().toISOString()};const id=$('updatesId').value;const q=id?await sb.from('site_updates').update(payload).eq('id',id):await sb.from('site_updates').insert(payload);status.textContent=q.error?q.error.message:'Atualização guardada.';if(!q.error)setTimeout(()=>location.reload(),500)};const rows=updates.filter(u=>u.id!==FALLBACK.id);$('updatesAdminList').innerHTML=rows.map(u=>`<div class="updates-admin-row"><span>${esc(u.version)} · ${esc(u.title)} · ${u.is_published?'Publicado':'Rascunho'}</span><button type="button" data-edit-update="${esc(u.id)}">Editar</button></div>`).join('');box.querySelectorAll('[data-edit-update]').forEach(btn=>btn.onclick=()=>{const u=updates.find(x=>String(x.id)===btn.dataset.editUpdate);if(!u)return;$('updatesId').value=u.id;$('updatesVersion').value=u.version;$('updatesTitle').value=u.title;$('updatesSummary').value=u.summary;$('updatesContent').value=u.content;$('updatesDate').value=u.published_at;$('updatesCategory').value=u.category;$('updatesPublished').value=String(u.is_published);window.scrollTo({top:box.offsetTop,behavior:'smooth'})})}
load();
})();
