-- Team Lambreta V92.39 — Buddy, perfil comunitário, bloqueios, denúncias e mensagens privadas somente texto

alter table public.profiles
  add column if not exists public_bio text,
  add column if not exists custom_avatar_url text,
  add column if not exists favorite_music text,
  add column if not exists main_game text,
  add column if not exists game_nickname_public text,
  add column if not exists social_links jsonb not null default '[]'::jsonb,
  add column if not exists profile_public boolean not null default true,
  add column if not exists level integer not null default 1,
  add column if not exists active_seconds bigint not null default 0,
  add column if not exists afk_seconds bigint not null default 0,
  add column if not exists live_seconds bigint not null default 0,
  add column if not exists forum_topics_count integer not null default 0;

create table if not exists public.buddy_relations (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  addressee_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','rejected')),
  requester_notify boolean not null default false,
  addressee_notify boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint buddy_relation_people_different check (requester_id <> addressee_id)
);
create unique index if not exists buddy_relations_unique_pair
on public.buddy_relations (least(requester_id,addressee_id), greatest(requester_id,addressee_id));

create table if not exists public.user_blocks (
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id,blocked_id),
  constraint user_blocks_people_different check (blocker_id <> blocked_id)
);

create table if not exists public.private_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now(),
  read_at timestamptz,
  hidden_by_sender boolean not null default false,
  hidden_by_receiver boolean not null default false,
  constraint private_message_people_different check (sender_id <> receiver_id)
);
create index if not exists private_messages_pair_time on public.private_messages(sender_id,receiver_id,created_at);

create table if not exists public.user_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  reported_id uuid not null references public.profiles(id) on delete cascade,
  reason text not null check (reason in ('assedio','spam','ameaca','conteudo_improprio','perfil_falso','outro')),
  details text check (char_length(coalesce(details,'')) <= 1000),
  status text not null default 'open' check (status in ('open','reviewing','closed')),
  created_at timestamptz not null default now(),
  constraint user_reports_people_different check (reporter_id <> reported_id)
);

alter table public.buddy_relations enable row level security;
alter table public.user_blocks enable row level security;
alter table public.private_messages enable row level security;
alter table public.user_reports enable row level security;

-- Perfis públicos para utilizadores autenticados; cada pessoa edita somente o próprio perfil.
grant select on public.profiles to authenticated;
grant update (public_bio,custom_avatar_url,favorite_music,main_game,game_nickname_public,social_links,profile_public) on public.profiles to authenticated;
drop policy if exists "profile owner community update" on public.profiles;
create policy "profile owner community update" on public.profiles for update to authenticated
using (id=auth.uid()) with check (id=auth.uid());

-- Buddy: apenas participantes enxergam e alteram a relação.
drop policy if exists "buddy participants select" on public.buddy_relations;
create policy "buddy participants select" on public.buddy_relations for select to authenticated
using (auth.uid() in (requester_id,addressee_id));
drop policy if exists "buddy requester insert" on public.buddy_relations;
create policy "buddy requester insert" on public.buddy_relations for insert to authenticated
with check (requester_id=auth.uid());
drop policy if exists "buddy participants update" on public.buddy_relations;
create policy "buddy participants update" on public.buddy_relations for update to authenticated
using (auth.uid() in (requester_id,addressee_id)) with check (auth.uid() in (requester_id,addressee_id));
drop policy if exists "buddy participants delete" on public.buddy_relations;
create policy "buddy participants delete" on public.buddy_relations for delete to authenticated
using (auth.uid() in (requester_id,addressee_id));

-- Bloqueios: somente o dono vê e administra sua lista.
drop policy if exists "block owner select" on public.user_blocks;
create policy "block owner select" on public.user_blocks for select to authenticated using (blocker_id=auth.uid());
drop policy if exists "block owner insert" on public.user_blocks;
create policy "block owner insert" on public.user_blocks for insert to authenticated with check (blocker_id=auth.uid());
drop policy if exists "block owner delete" on public.user_blocks;
create policy "block owner delete" on public.user_blocks for delete to authenticated using (blocker_id=auth.uid());

-- Mensagens privadas: somente remetente e destinatário; bloqueio impede novas mensagens.
drop policy if exists "private message participants select" on public.private_messages;
create policy "private message participants select" on public.private_messages for select to authenticated
using (auth.uid() in (sender_id,receiver_id));
drop policy if exists "private message sender insert" on public.private_messages;
create policy "private message sender insert" on public.private_messages for insert to authenticated
with check (
  sender_id=auth.uid()
  and not exists (
    select 1 from public.user_blocks b
    where (b.blocker_id=receiver_id and b.blocked_id=sender_id)
       or (b.blocker_id=sender_id and b.blocked_id=receiver_id)
  )
);
drop policy if exists "private message participants update" on public.private_messages;
create policy "private message participants update" on public.private_messages for update to authenticated
using (auth.uid() in (sender_id,receiver_id)) with check (auth.uid() in (sender_id,receiver_id));

-- Denúncias: criador insere; apenas equipa administrativa consulta.
drop policy if exists "reporter insert" on public.user_reports;
create policy "reporter insert" on public.user_reports for insert to authenticated with check (reporter_id=auth.uid());
drop policy if exists "reporter own select" on public.user_reports;
create policy "reporter own select" on public.user_reports for select to authenticated
using (
  reporter_id=auth.uid() or exists (
    select 1 from public.profiles p where p.id=auth.uid() and p.role in ('master','admin','moderator','staff')
  )
);

grant select,insert,update,delete on public.buddy_relations to authenticated;
grant select,insert,delete on public.user_blocks to authenticated;
grant select,insert,update on public.private_messages to authenticated;
grant select,insert on public.user_reports to authenticated;
grant usage,select on all sequences in schema public to authenticated;

-- Bucket opcional para avatar personalizado.
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('profile-avatars','profile-avatars',true,5242880,array['image/jpeg','image/png','image/webp'])
on conflict (id) do nothing;

drop policy if exists "avatar public read" on storage.objects;
create policy "avatar public read" on storage.objects for select using (bucket_id='profile-avatars');
drop policy if exists "avatar owner upload" on storage.objects;
create policy "avatar owner upload" on storage.objects for insert to authenticated
with check (bucket_id='profile-avatars' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists "avatar owner update" on storage.objects;
create policy "avatar owner update" on storage.objects for update to authenticated
using (bucket_id='profile-avatars' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists "avatar owner delete" on storage.objects;
create policy "avatar owner delete" on storage.objects for delete to authenticated
using (bucket_id='profile-avatars' and (storage.foldername(name))[1]=auth.uid()::text);
