-- Fórum canónico: categoria -> pasta -> tópico -> posts.
-- Preserva os registos de atividade existentes e mantém a atribuição de XP atual.
begin;

create table if not exists public.forum_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text not null default '',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.forum_sections (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.forum_categories(id) on delete restrict,
  parent_id bigint references public.forum_sections(id) on delete restrict,
  slug text not null unique,
  name text not null,
  description text not null default '',
  sort_order integer not null default 0,
  is_private boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.forum_topics (
  id text primary key,
  section_id bigint not null references public.forum_sections(id) on delete restrict,
  author_id uuid not null references public.profiles(id) on delete restrict,
  title text not null check (char_length(title) between 1 and 120),
  body text not null check (char_length(body) between 1 and 5000),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  is_private boolean not null default false,
  is_pinned boolean not null default false,
  is_locked boolean not null default false,
  view_count integer not null default 0 check (view_count >= 0),
  approved_by uuid references public.profiles(id) on delete set null,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_activity_at timestamptz not null default now()
);

create table if not exists public.forum_posts (
  id text primary key,
  topic_id text not null references public.forum_topics(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete restrict,
  body text not null check (char_length(body) between 1 and 5000),
  is_original boolean not null default false,
  is_private boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (topic_id, id)
);

create unique index if not exists forum_posts_one_original
  on public.forum_posts(topic_id) where is_original;
create index if not exists forum_topics_section_activity
  on public.forum_topics(section_id, status, is_pinned desc, last_activity_at desc);
create index if not exists forum_posts_topic_created
  on public.forum_posts(topic_id, created_at);

create table if not exists public.forum_topic_views (
  topic_id text not null references public.forum_topics(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  viewed_on date not null default current_date,
  created_at timestamptz not null default now(),
  primary key(topic_id, user_id, viewed_on)
);

insert into public.forum_categories(slug,name,description,sort_order) values
  ('competitivo','Competitivo','Jogos, torneios e evolução competitiva.',10),
  ('team-lambreta','Team Lambreta','Informações e atividades oficiais da equipa.',20),
  ('comunidade','Comunidade','Conversas e conteúdo dos membros.',30),
  ('suporte','Suporte','Ajuda com o site, conta e problemas técnicos.',40),
  ('area-privada','Área privada','Pastas reservadas ao autor e à moderação.',50)
on conflict(slug) do update set
  name=excluded.name,description=excluded.description,sort_order=excluded.sort_order;

insert into public.forum_sections(category_id,slug,name,description,sort_order,is_private)
select c.id,v.slug,v.name,v.description,v.sort_order,v.is_private
from (values
  ('competitivo','fortnite','Fortnite','Partidas, equipas e novidades de Fortnite.',10,false),
  ('competitivo','torneios','Torneios','Inscrições, regras e organização de torneios.',20,false),
  ('competitivo','estrategias','Estratégias','Táticas, treino e evolução competitiva.',30,false),
  ('competitivo','procurando-equipa','Procurando equipa','Encontre membros para jogar e competir.',40,false),
  ('competitivo','resultados','Resultados','Resultados e destaques competitivos.',50,false),
  ('team-lambreta','avisos-oficiais','Avisos oficiais','Comunicados oficiais do Team Lambreta.',10,false),
  ('team-lambreta','recrutamento','Recrutamento','Informações e dúvidas sobre recrutamento.',20,false),
  ('team-lambreta','eventos','Eventos','Eventos e atividades da equipa.',30,false),
  ('team-lambreta','sugestoes','Sugestões','Ideias para melhorar o Team e a comunidade.',40,false),
  ('comunidade','geral','Geral','Conversas gerais da comunidade.',10,false),
  ('comunidade','apresentacoes','Apresentações','Apresente-se aos outros membros.',20,false),
  ('comunidade','clips-videos','Clips e vídeos','Partilhe clips, vídeos e momentos.',30,false),
  ('comunidade','off-topic','Off-topic','Conversas que não cabem nas outras pastas.',40,false),
  ('suporte','site','Site','Ajuda com páginas e funções do site.',10,false),
  ('suporte','conta','Conta','Ajuda com acesso e conta.',20,false),
  ('suporte','bugs','Bugs','Relate comportamentos inesperados.',30,false),
  ('suporte','loja','Loja','Pedidos, pagamentos, entregas e tamanhos.',40,false),
  ('suporte','duvidas','Dúvidas','Perguntas e respostas da comunidade.',50,false),
  ('area-privada','candidaturas','Candidaturas','Candidaturas visíveis ao autor e à moderação.',10,true),
  ('area-privada','denuncias','Denúncias','Denúncias visíveis ao autor e à moderação.',20,true)
) as v(category_slug,slug,name,description,sort_order,is_private)
join public.forum_categories c on c.slug=v.category_slug
on conflict(slug) do update set
  category_id=excluded.category_id,name=excluded.name,description=excluded.description,
  sort_order=excluded.sort_order,is_private=excluded.is_private;

-- Promove os tópicos que já sustentavam o XP para a estrutura canónica.
insert into public.forum_topics(
  id,section_id,author_id,title,body,status,is_private,created_at,updated_at,last_activity_at
)
select t.topic_key,s.id,t.user_id,t.title,t.body,
       case when t.is_approved then 'approved' else 'pending' end,
       t.is_private,t.created_at,t.created_at,
       coalesce((select max(r.created_at) from public.forum_activity_replies r where r.topic_key=t.topic_key),t.created_at)
from public.forum_activity_topics t
join public.forum_sections s on s.slug=(case t.category
  when 'suporte' then 'site' when 'loja' then 'loja' when 'sugestoes' then 'sugestoes'
  when 'duvidas' then 'duvidas' when 'ajuda' then 'duvidas' when 'candidaturas' then 'candidaturas'
  when 'eventos' then 'eventos' when 'fortnite' then 'fortnite' when 'denuncias' then 'denuncias'
  else 'geral' end)
on conflict(id) do nothing;

insert into public.forum_posts(id,topic_id,author_id,body,is_original,is_private,created_at,updated_at)
select 'original_'||t.topic_key,t.topic_key,t.user_id,t.body,true,t.is_private,t.created_at,t.created_at
from public.forum_activity_topics t
join public.forum_topics ft on ft.id=t.topic_key
on conflict(id) do nothing;

insert into public.forum_posts(id,topic_id,author_id,body,is_original,is_private,created_at,updated_at)
select r.reply_key,r.topic_key,r.user_id,r.body,false,r.is_private,r.created_at,r.created_at
from public.forum_activity_replies r
join public.forum_topics ft on ft.id=r.topic_key
on conflict(id) do nothing;

create or replace function public.tl_is_forum_moderator(p_user_id uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public
as $$
  select exists(
    select 1 from public.profiles p
    where p.id=p_user_id and lower(p.role::text) in ('master','dev','admin','staff','moderator','moderador','boss')
  );
$$;
revoke all on function public.tl_is_forum_moderator(uuid) from public;
grant execute on function public.tl_is_forum_moderator(uuid) to authenticated;

alter table public.forum_categories enable row level security;
alter table public.forum_sections enable row level security;
alter table public.forum_topics enable row level security;
alter table public.forum_posts enable row level security;
alter table public.forum_topic_views enable row level security;

drop policy if exists forum_categories_members_read on public.forum_categories;
create policy forum_categories_members_read on public.forum_categories for select to authenticated
using (is_active);
drop policy if exists forum_sections_members_read on public.forum_sections;
create policy forum_sections_members_read on public.forum_sections for select to authenticated
using (is_active);
drop policy if exists forum_topics_members_read on public.forum_topics;
create policy forum_topics_members_read on public.forum_topics for select to authenticated
using (
  (status='approved' or author_id=auth.uid() or public.tl_is_forum_moderator())
  and (not is_private or author_id=auth.uid() or public.tl_is_forum_moderator())
);
drop policy if exists forum_posts_members_read on public.forum_posts;
create policy forum_posts_members_read on public.forum_posts for select to authenticated
using (
  exists(select 1 from public.forum_topics t where t.id=topic_id)
  and (not is_private or author_id=auth.uid() or public.tl_is_forum_moderator())
);

revoke all on public.forum_categories,public.forum_sections,public.forum_topics,public.forum_posts,public.forum_topic_views from anon;
revoke insert,update,delete on public.forum_categories,public.forum_sections,public.forum_topics,public.forum_posts,public.forum_topic_views from authenticated;
grant select on public.forum_categories,public.forum_sections,public.forum_topics,public.forum_posts to authenticated;

create or replace function public.tl_forum_create_topic_v2(
  p_section_id bigint,p_title text,p_body text
) returns jsonb language plpgsql security definer set search_path=public
as $$
declare
  v_uid uuid:=auth.uid(); v_id text; v_post_id text; v_private boolean; v_status text;
begin
  if v_uid is null then raise exception 'Login necessário'; end if;
  if char_length(trim(p_title)) not between 1 and 120 or char_length(trim(p_body)) not between 1 and 5000 then
    raise exception 'Conteúdo do tópico inválido';
  end if;
  select is_private into v_private from public.forum_sections where id=p_section_id and is_active;
  if not found then raise exception 'Pasta inválida'; end if;
  if (select count(*) from public.forum_topics where author_id=v_uid and created_at>now()-interval '1 hour')>=10 then
    raise exception 'Limite de tópicos por hora atingido';
  end if;
  v_id:='topic_'||replace(gen_random_uuid()::text,'-','');
  v_post_id:='post_'||replace(gen_random_uuid()::text,'-','');
  v_status:=case when public.tl_is_forum_moderator(v_uid) then 'approved' else 'pending' end;
  insert into public.forum_topics(id,section_id,author_id,title,body,status,is_private,approved_by,approved_at)
  values(v_id,p_section_id,v_uid,trim(p_title),trim(p_body),v_status,v_private,
         case when v_status='approved' then v_uid end,case when v_status='approved' then now() end);
  insert into public.forum_posts(id,topic_id,author_id,body,is_original,is_private)
  values(v_post_id,v_id,v_uid,trim(p_body),true,v_private);
  if v_status='approved' then perform public.tl_award_forum_xp(v_uid,'forum_topic','topic:'||v_id,20); end if;
  return jsonb_build_object('id',v_id,'post_id',v_post_id,'status',v_status);
end;
$$;

create or replace function public.tl_forum_create_post_v2(p_topic_id text,p_body text)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare v_uid uuid:=auth.uid(); v_id text; v_private boolean;
begin
  if v_uid is null then raise exception 'Login necessário'; end if;
  if char_length(trim(p_body)) not between 1 and 5000 then raise exception 'Resposta inválida'; end if;
  select is_private into v_private from public.forum_topics
  where id=p_topic_id and status='approved' and not is_locked
    and (not is_private or author_id=v_uid or public.tl_is_forum_moderator(v_uid));
  if not found then raise exception 'Tópico indisponível ou fechado'; end if;
  if (select count(*) from public.forum_posts where author_id=v_uid and created_at>now()-interval '1 hour')>=50 then
    raise exception 'Limite de respostas por hora atingido';
  end if;
  v_id:='post_'||replace(gen_random_uuid()::text,'-','');
  insert into public.forum_posts(id,topic_id,author_id,body,is_private)
  values(v_id,p_topic_id,v_uid,trim(p_body),v_private);
  update public.forum_topics set updated_at=now(),last_activity_at=now() where id=p_topic_id;
  perform public.tl_award_forum_xp(v_uid,'forum_reply','reply:'||v_id,8);
  return jsonb_build_object('id',v_id,'topic_id',p_topic_id);
end;
$$;

create or replace function public.tl_forum_moderate_topic_v2(
  p_topic_id text,p_action text,p_section_id bigint default null
) returns jsonb language plpgsql security definer set search_path=public
as $$
declare v_uid uuid:=auth.uid(); v_topic public.forum_topics; v_was_approved boolean;
begin
  if not public.tl_is_forum_moderator(v_uid) then raise exception 'Sem permissão'; end if;
  select * into v_topic from public.forum_topics where id=p_topic_id for update;
  if not found then raise exception 'Tópico não encontrado'; end if;
  v_was_approved:=v_topic.status='approved';
  case lower(p_action)
    when 'approve' then
      update public.forum_topics set status='approved',approved_by=v_uid,approved_at=coalesce(approved_at,now()),updated_at=now() where id=p_topic_id;
      if not v_was_approved then perform public.tl_award_forum_xp(v_topic.author_id,'forum_topic','topic:'||p_topic_id,20); end if;
    when 'reject' then update public.forum_topics set status='rejected',updated_at=now() where id=p_topic_id;
    when 'pin' then update public.forum_topics set is_pinned=true,updated_at=now() where id=p_topic_id;
    when 'unpin' then update public.forum_topics set is_pinned=false,updated_at=now() where id=p_topic_id;
    when 'lock' then update public.forum_topics set is_locked=true,updated_at=now() where id=p_topic_id;
    when 'unlock' then update public.forum_topics set is_locked=false,updated_at=now() where id=p_topic_id;
    when 'move' then
      if not exists(select 1 from public.forum_sections where id=p_section_id and is_active) then raise exception 'Pasta inválida'; end if;
      update public.forum_topics t set section_id=p_section_id,is_private=s.is_private,updated_at=now()
      from public.forum_sections s where t.id=p_topic_id and s.id=p_section_id;
      update public.forum_posts p set is_private=t.is_private from public.forum_topics t where p.topic_id=t.id and t.id=p_topic_id;
    else raise exception 'Ação inválida';
  end case;
  return jsonb_build_object('id',p_topic_id,'action',lower(p_action));
end;
$$;

create or replace function public.tl_forum_register_view(p_topic_id text)
returns integer language plpgsql security definer set search_path=public
as $$
declare v_uid uuid:=auth.uid(); v_inserted integer;
begin
  if v_uid is null then raise exception 'Login necessário'; end if;
  if not exists(select 1 from public.forum_topics where id=p_topic_id and status='approved') then raise exception 'Tópico indisponível'; end if;
  insert into public.forum_topic_views(topic_id,user_id) values(p_topic_id,v_uid) on conflict do nothing;
  get diagnostics v_inserted=row_count;
  if v_inserted=1 then update public.forum_topics set view_count=view_count+1 where id=p_topic_id; end if;
  return (select view_count from public.forum_topics where id=p_topic_id);
end;
$$;

revoke all on function public.tl_forum_create_topic_v2(bigint,text,text) from public;
revoke all on function public.tl_forum_create_post_v2(text,text) from public;
revoke all on function public.tl_forum_moderate_topic_v2(text,text,bigint) from public;
revoke all on function public.tl_forum_register_view(text) from public;
grant execute on function public.tl_forum_create_topic_v2(bigint,text,text) to authenticated;
grant execute on function public.tl_forum_create_post_v2(text,text) to authenticated;
grant execute on function public.tl_forum_moderate_topic_v2(text,text,bigint) to authenticated;
grant execute on function public.tl_forum_register_view(text) to authenticated;

commit;
